### ISSUE TITLE
Bug: Scaling Issue in Luban 3.15.1

### ISSUE THREAD

**Issue by 0x49b** [Snapmaker/Luban#1012]
# 🐞 bug report

### Affected Version(s)

 The issue is caused by version 3.15.1

### To Reproduce
1. Go to 3D Printing
2. Add 2 .stl in the workbench
3. Choose one of the objects
4. open scaling
5. add any scaling
6. choose the other object
7. scaling does not get reset for new object

Exception or Error (optional)
<pre><code>
No Exception is displayed (not necessary)
</code></pre>

Expected behavior

The scaling entered should be reset when selecting a new object. If the input box losts focus, the false object will be scaled

Refer to this screencapture for better explanantion: [https://youtu.be/4qmXpXtIRVg](https://youtu.be/4qmXpXtIRVg)

## 🌍  Your Environment

**Platform:**
<pre><code>
- Operating System: Windows 10 x64 & macOS Big Sur (tested on both)
- Printer:  Snapmaker A250

</code></pre>

**Comment by jane-rose** [comment]
Known bug, will be fixed soon.
