### ISSUE TITLE
Feature Request: Is there really  no way to "select all" objects to make a toolpath??

### ISSUE THREAD

**Issue by Galindorf** [Snapmaker/Luban#1018]
# 🐞 feature request

### Is your feature request related to a problem? Please describe.

The object/path handling in the laser portion of Luban is so frustrating. You can choose all the objects in "edit" but as soon as you go to "Process" they are unselected. I need to choose multiple objects to create a single toolpath with all the same properties. 

### Describe the solution you'd like?

There needs to be a way to select multiple objects in Edit mode. if I drag+click all it does is turn the position of the workspace. There is no list of the objects, you have to click in the workspace to select them, and the commonly disappear behind the workspace in Process mode so you can't even see them in the first place.  See Photo:
![image](https://user-images.githubusercontent.com/17105217/121088951-1412a280-c7ac-11eb-997f-63cb8866ac93.png)

I have twelve separate objects on this, and no way to select them? That's crazy. I feel like I'm fighting all the time with this software to do basic things like "undo" or "delete" or line up a view. Why is there a trash can to delete toolpaths in the "toolpath list" but not one to delete objects in the "object list?" You just have to magically know to hit "delete" even though you DON'T have to on the other list? Why won't it save any previous settings?? I have to adjust everything in Luban every time I do a laser cutting job. Apologies for the rant.

**Comment by jane-rose** [comment]
Sorry for that happended. In 'Process', you can use 'ctrl + a' or 'shift + click' to select multiple objects to create toolpath. We will consider it if is necessary to add object list in 'Process'. As for the first disappearence, you can see the object by rotating the view.
