### ISSUE TITLE
CNC 4 axis scaling error

### ISSUE THREAD

**Issue by theRealPDXMike** [Snapmaker/Luban#1031]
1. Luban 3.15.1
2. set stock size (I used a 51mm diameter X 95 mm round piece (work area should be 160.22mm X 90ish mm)
3. imported a .stl file
4. moved and sized the flattened model to fit in the carving area ( I left it locked and set the W to 159.2 X 53.1 mm H)
5. checked the preview to make sure the model was very close to filling the diameter without clipping.
6. Processed the file, saved the .cnc file to disk.
7. loaded file to A350, set origin and started.
8. machine milled about 5-6 mm deep before it started machining the actual model
9. Actual model came out to roughly 37mm in diameter!
10.
I expected the model to be much larger than what Luban processed onto the .cnc file.

**Comment by jane-rose** [comment]
Could you send us the project file?
