### ISSUE TITLE
Bug: Scaling in 3d printing

### ISSUE THREAD

**Issue by rstocks** [Snapmaker/Luban#1171]
# 🐞 bug report

### Affected Version(s)
The issue is caused by version 4.0.0

### Is this a regression?
Yes - works as expected in 3.15.2

### To Reproduce
1. Add an STL file to the 3D printing module
2. Click on "Scaling"
3. Make sure "Uniform scaling" is not selected
4. Change the scale factor of any axis
5. The other two axis change as well

Expected behavior
Only the modified axis should be scaled.

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: macOS Monterey
- Printer: A350

</code></pre>

**Comment by parachvte** [comment]
Fixed in v4.0.1
