### ISSUE TITLE
Bug: wrong fonts in some views

### ISSUE THREAD

**Issue by 0x49b** [Snapmaker/Luban#1179]
# 🐞 bug report

### Affected Version(s)

 The issue is caused by version 4.0.1

### Is this a regression? (optional)

 Yes, the previous version in which this bug was not present was: ....
In 3.15 all fonts were OK

### To Reproduce
Just open Luban

Exception or Error (optional)
Expected behavior

All fonts have to be loaded correctly --> Examples with fails see screenshot

## 🌍  Your Environment

**Platform:**
<pre><code>
- Operating System: [Windows 10 x64, macOS Big Sur]
- Printer: [Snapmaker A250]

</code></pre>
![CNC_Font_Fail](https://user-images.githubusercontent.com/2895704/130916325-d3b4f7e3-7e26-41fe-be1b-80b64fc2bb05.png)
![3D_Printing_Font_Fail](https://user-images.githubusercontent.com/2895704/130916331-13890012-f28d-4688-971c-729db8d879d9.png)
![Home_Font_Fail](https://user-images.githubusercontent.com/2895704/130916332-b6444459-7231-46f9-a42b-062ff7293aa2.png)

**Comment by nichtraunzer** [comment]
I second that - this mixture of different font causes eye cancer (Platform Mac OS M1 latest)

**Comment by thmsnhl** [comment]
I have prepared a fix for this, but I am not able to push a branch to the repository. 
Should I create a fork of this repo and provide it there or is there another way around this?

**Comment by parachvte** [comment]
> I have prepared a fix for this, but I am not able to push a branch to the repository. Should I create a fork of this repo and provide it there or is there another way around this?

Fork, and open a new pull request.
