### ISSUE TITLE
Bug: timecalculations wrong for lasercutting/laseretching

### ISSUE THREAD

**Issue by 0x49b** [Snapmaker/Luban#1203]
# 🐞 bug report

### Affected Version(s)
The issue is caused in Luban 4.0.2

### Is this a regression? (optional)
The issues did not happen in prior versions to 4.x.x

### To Reproduce
1. Create a design
2. load into Luban Laser module
3. generate .nc
4. see calculated time

Expected behavior
The time calculations should be preciser. Calculated time by Luban was 1h 42 min. Effective laser etching took 4h 22min. Screenshot from Luban:
![time_calculation_luban](https://user-images.githubusercontent.com/2895704/133882610-a67842a2-b9c0-452f-9283-d0dd8723d678.png)

## 🌍  Your Environment
- Operating System: Windows 10 x64, macOS Big Sur
- Printer: A250

**Comment by F1nnM** [comment]
I'd like to add that there are also cases, where luban seriously overestimates the time.
With fill:dots it calculates about three times as much time as it actually takes, in my cases at least.

**Comment by sumibin** [comment]
We have optimized the motion part of the firmware, as well as the time firmware of Luban at the same time. This issue will be closed.
