### ISSUE TITLE
Bug: Dodgy GCode in 3d printing

### ISSUE THREAD

**Issue by tyeth** [Snapmaker/Luban#1206]
# 🐞 bug report

### Affected Version(s)
4.0.3

### To Reproduce
1. Set machine to A350, do something close and reopen luban. Set machine to Snapmaker original. do something, close and reload luban.
2. Click on "Fabric" / chain-mail 3dp sample in Case Study panel of Luban 
3. Accept defaults of Normal quality, PLA, and generate and export gcode.
4. Take via USB to snapmaker, or dont bother just read gcode and **spot the issue, temp is 215c**, but clearly states in PLA material settings 205.
5. Also notice seriously long base64 thumbnail included as comment in gcode, is this actually used because my snapmaker2 has never loaded one preview so far just white box and the snapmaker1 I just got has no such feature as preview (nor bed/nozzle temp adjust mid print but old firmware so will update before bug report).

Expected behavior
Material and Quality settings should be adhered to.
Fabric Gcode generated by luban 4.0.3 linked here:
https://gist.github.com/tyeth/8a916517e061cddc9b6a93a1df18eeee

## 🌍  Your Environment

**Platform:**
- Operating System: Windows 10 x64
- Printer: Snapmaker Original first print (had luban setup for my snapmaker A350 hence the reproduction steps)

**Comment by sumibin** [comment]
1. "Fabric" Temp : We confirmed that the temperature of the case was 205 ℃(PLA). Maybe you changed the parameters in PLA?
![image](https://user-images.githubusercontent.com/34013829/134268603-4d5f9a37-1d92-4008-a83c-2d08ba669c18.png)

2. Thumbnail : This feature can cause a serious exception, so we went offline it at 4.0.**We'll fix it in 4.1.**

**Comment by tyeth** [comment]
No, it's clearer now, I reload the app and the default selected PLA isn't respected. If I then select ABS it generates the correct GCODE, if I then select PLA it correctly uses 205, if I then shut Luban and reload it, selecting the fabric example again then generate gcode it is back at 215c. If I select the materials dropdown and reclick on PLA it still is 215.
 I have to select a different material and then back to PLA to get it to respect PLA after first loading the program and example print (fabric)

**Comment by tyeth** [comment]
I can provide gcode (and a video) if really necessary

**Comment by tyeth** [comment]
This sounds like maybe I once set PLA to 215, and due to you implementing remembering last user value then when luban loads it uses an old user value and confusingly lists that PLA is selected (which is true but the temp value doesn't match the PLA temp value due to being a remembered and unforgettable user set value) meaning the user can't tell if the PLA profile is being used or a modified set of values. 
Related #1180

**Comment by sumibin** [comment]
This problem should have been solved by now
