### ISSUE TITLE
CNC module crashes under Ubuntu Linux

### ISSUE THREAD

**Issue by ozzyman** [Snapmaker/Luban#1214]
The CNC module in luban V4.0.3 (also V4.0.0) fails to create toolpaths on Ubuntu Linux. 

Steps to produce error:

1. In CNC Edit screen, place an object (e,g a circle)
2. Click "process" or "next" and ensure object is selected (has blue box around it)
3. Click "create toolpath" 
         The screen goes blank with a menu bar at the top. Nothing else happens. 
4. Select "reload" from the "Window" menu
         Luban crashes and restarts. 

Bug is new in version 4.0.x  Toolpath creation works as expected in version 3.15

![Luban screen-1](https://user-images.githubusercontent.com/4989367/134870027-83414e68-4bc7-4a47-827f-023ec50e2326.png)
![Luban screen-2](https://user-images.githubusercontent.com/4989367/134870034-6ec64168-f053-4c41-8cd2-6477636c6fda.png)
![Luban screen-3](https://user-images.githubusercontent.com/4989367/134870036-df343dd3-dc1e-414b-ae3c-8d2efb6c4e23.png)
![Luban screen-4](https://user-images.githubusercontent.com/4989367/134870039-66ace321-3066-45a7-92fd-7ae7070fd5d4.png)
.2

**Comment by raivonigul** [comment]
I have same issue. Ealier version of Luban works properly. Current version works propely on Windows. In Linux the toolpath dialog are created - wisible on task bar as double Icon but not visible on workspace

**Comment by ozzyman** [comment]
I don't even see the second window under Ubuntu 20.04

**Comment by deimi** [comment]
It seems that it works with v4.1.0-beta.1

**Comment by jane-rose** [comment]
Yes, it is fixed in v4.1.x version. But the beta version is unstable, please update to the official version 4.1.1 or later.

> It seems that it works with v4.1.0-beta.1
