### ISSUE TITLE
Bug: Transform in SVG causes path parsing issues for laser

### ISSUE THREAD

**Issue by rbcapp** [Snapmaker/Luban#1216]
# 🐞 bug report

### Affected Version(s)
The issue is found in version 4.0.3

### Is this a regression? (optional)
It is unknown if this is a regression.

### To Reproduce

1. Load SVG containing a transform into the laser work. (Example created using Inkscape)
2. Set Object processing mode to Vector
3. Move to Process mode
4. Create toolpath with On the Path
5. Generate G-Code and Preview
6. See error

Exception or Error (optional)
Instead of creating a path that matches the initial image, the created path is reduced to a single line.

Expected behavior

The steps should create a proper path for the laser to trace. (The example should create a book cover image.)

## 🌍  Your Environment

**Platform:**
<pre><code>
- Operating System: Windows 10 x64
- Printer: Snapmaker A350
</code></pre>

SVG Example
`<svg xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" width="102mm" height="64mm" viewBox="0 0 102 64" version="1.1" id="svg2593" inkscape:version="1.1 (c68e22c387, 2021-05-23)" sodipodi:docname="GloomhavenCard Storage Front Wall(A7) Experiment.tar">
  <sodipodi:namedview id="namedview2595" pagecolor="#505050" bordercolor="#eeeeee" borderopacity="1" inkscape:pageshadow="0" inkscape:pageopacity="0" inkscape:pagecheckerboard="0" inkscape:document-units="mm" showgrid="false" showguides="true" inkscape:guide-bbox="true" inkscape:zoom="11.313709" inkscape:cx="183.05226" inkscape:cy="53.784307" inkscape:window-width="3440" inkscape:window-height="1377" inkscape:window-x="1912" inkscape:window-y="-8" inkscape:window-maximized="1" inkscape:current-layer="layer8">
    <sodipodi:guide position="50.99947,36.948421" orientation="1,0" id="guide1375"/>
    <sodipodi:guide position="107.10826,11.98935" orientation="0,-1" id="guide1392"/>
  </sodipodi:namedview>
  <defs id="defs2590">
    <clipPath clipPathUnits="userSpaceOnUse" id="clipPath1116">
      <path d="M 0,0 H 299 V 300 H 0 Z" id="path1114"/>
    </clipPath>
    <clipPath clipPathUnits="userSpaceOnUse" id="clipPath949">
      <path d="M 0,0 H 300 V 300 H 0 Z" id="path947"/>
    </clipPath>
  </defs>
  <g inkscape:groupmode="layer" id="layer8" inkscape:label="Book Cover" style="display:inline">
    <path id="path1702" style="display:inline;opacity:0.479675;vector-effect:non-scaling-stroke;fill:#007700;fill-opacity:0.480186;stroke:#0000ff;stroke-width:0.00231772;stroke-linejoin:round;stroke-opacity:1;-inkscape-stroke:hairline;paint-order:markers fill stroke" d="m 211.65625,8.4882812 c -0.14615,0.00522 -0.30109,0.01918 -0.42578,0.044922 -1.91178,0.3951292 -5.79365,0.8076357 -9.2207,0.9785157 -0.48032,0.023924 -1.51389,0.1155868 -2.93555,0.2539062 l -44.00781,5.2207029 0.76367,9.492188 c 3.72026,-0.402117 23.18957,-2.453662 23.67773,-2.298828 0.5647,0.179119 5.53067,5.95576 5.55078,6.486328 0.0189,0.530558 -3.9556,7.140651 -4.47851,7.509765 -0.48157,0.339973 -20.64118,2.312709 -23.5957,2.642578 l 2.74023,34.253907 c 1.36682,-0.179074 2.61756,-0.537987 3.38867,-0.660157 2.84068,-0.450122 12.79445,-1.468057 14.55274,-1.74414 3.27881,-0.514806 6.81578,-0.665486 6.97851,-0.617188 0.32553,0.09645 5.56579,5.790013 5.60547,6.283203 0.0287,0.373531 -4.40842,7.152882 -4.72461,7.414063 -0.31325,0.258746 -24.2061,3.290309 -24.6582,3.347656 l 1.04687,13.007817 58.25977,-6.910161 c -1.26496,-13.575314 -5.55604,-49.692647 -5.34766,-57.027343 0.253,-8.906859 -1.52056,-21.787004 -1.67969,-23.109375 -0.28346,-2.355463 0.35783,-4.457585 -1.11718,-4.5644534 -0.0906,-0.00639 -0.22674,-0.00893 -0.37305,-0.00391 z m -8.44336,6.9160158 h 0.002 c 0.0909,-9.76e-4 0.76269,0.190733 0.79883,0.242187 0.0363,0.05175 -0.3164,0.822266 -0.3164,0.822266 0,0 0.41096,4.347685 0.56445,5.064453 0.4707,0.03413 2.50195,0.03516 2.50195,0.03516 -0.0351,-0.319347 0.68638,-0.429418 0.75586,0.0625 0.0695,0.491611 -0.67354,0.533745 -0.72656,0.246094 l -1.83789,0.326172 1.41992,17.900391 -1.06641,1.421875 -1.26367,-1.119141 -1.39844,-17.951172 -1.95703,-0.05078 c 0.0185,0.310703 -0.76448,0.523346 -0.76172,-0.04883 0.008,-0.572806 0.72155,-0.424255 0.74024,-0.183594 0.0516,0.0064 2.36523,-0.476562 2.36523,-0.476563 l -0.20117,-5.167968 c 0,0 -0.52775,-0.629405 -0.51367,-0.695313 0.0184,-0.06569 0.8019,-0.421964 0.89453,-0.427734 z" transform="scale(0.26458333)"/>
  </g>
  </svg>`

Note the transform at the end of the file. Removing that will generate a correct path (though improperly scaled.)

**Comment by sumibin** [comment]
This issue should currently be fixed.
