### ISSUE TITLE
Feature Request: Option to disable fan for initial layers when 3D printing

### ISSUE THREAD

**Issue by wdecook** [Snapmaker/Luban#1237]
Sometimes, it's just impossible to get that first layer down without it warping and pulling up off the board.

In this case, it would be handy to be able to disable the cooling fans for the initial layer(s) in order to slow the cooling of the filament as it comes out of the hot end and decrease the likelihood of warping.

**Comment by pavolzibrita** [comment]
Some filaments suggest that, e.g. https://www.amazon.ca/gp/product/B09DKP4TLW/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&th=1 

```
【Note - turn off the fan for the first layer for improved bed adhesion】
```

**Comment by sumibin** [comment]
This feature has been released.

**Comment by parachvte** [comment]
![image](https://user-images.githubusercontent.com/3749551/226789848-2a9abae4-35ba-46cb-af9d-3e29cad00dca.png)

By using "All" filter, you can see the "Regular Fan Speed at Layer = 2".

By default, the fan should be off for first few layers (Initial Layer Optimization -> Initial Fan Speed = 0%), and starts to work at regular speed from layer 2.
