### ISSUE TITLE
Feature Request: Add 3MF support in Luban

### ISSUE THREAD

**Issue by Jonnie-Cache** [Snapmaker/Luban#1239]
# 🐞 feature request

### Is your feature request related to a problem? Please describe.

3MF is now the standard file format for 3D models. It is supported by software from Microsoft, Ultimaker, Prusa, Autodesk, and others. STL is less efficient and more error prone than 3MF. 3MF includes additional information, including color information that is important. See: https://3mf.io/adoption/

### Describe the solution you'd like?

Please add support for 3MF in Luban! 😀

**Comment by sumibin** [comment]
This feature has been released.

**Comment by lietu** [comment]
Then why does Luban tell me `Failed to import this object. Please select a supported file format.` every time I try to load a .3mf file?
