### ISSUE TITLE
.svg files scaled incorrectly in CNC workspace

### ISSUE THREAD

**Issue by ozzyman** [Snapmaker/Luban#1241]
### Affected Version(s)
All versions since 3.08. Persisted in 3.15 and affects v4.03

### To Reproduce
1. open CNC workspace
2. Click on "add file" and select an .svg file

### Expected behavior
File should open in the editor space scaled as 1:1. i.e a 50mmx 50mm square drawn in Inkscape and saved as a plain .svg should open as a 50mmx50mm square in Luban

### Actual beghaviour
File opens in Luban scaled by a factor of about 1.2:1.

## 🌍  Your Environment

- Operating System: Windows 10 x64, Ubuntu 20.04
- Printer: Snapmaker A350

**Comment by sumibin** [comment]
The issue has been fixed.
