### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported -- node v17 gives trouble -- error in webpack

### ISSUE THREAD

**Issue by tyeth** [Snapmaker/Luban#1250]
Running on WSL (ubuntu in windows11) and updated to node v17, cleaned and ran build project but dies with error:
```
[13:57:21] 'appBuildProduction' errored after 1.53 min
[13:57:21] Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports
```

![image](https://user-images.githubusercontent.com/6692083/139072810-b412c990-69e9-491a-b8b3-f6dc83d44c08.png)

**Issue** is actually with node v17 and webpack, see here: https://github.com/webpack/webpack/issues/14532

**Solution** is only for node v17 as breaks <=16
```export NODE_OPTIONS=--openssl-legacy-provider```

**Comment by 0xPasho** [comment]
Hey man, found a workaround for this, execute:
```
export NODE_OPTIONS=--openssl-legacy-provider
```
Workaround took from https://github.com/webpack/webpack/issues/14532#issuecomment-947012063

**Comment by parachvte** [comment]
We will upgrade webpack to v5 when it's been fixed and stabilized.
I'm closing this issue.
