### ISSUE TITLE
Bug: 4-axis laser (and possibly CNC) has confusing x-axis origin rendering

### ISSUE THREAD

**Issue by maihde** [Snapmaker/Luban#1301]
# 🐞 bug report

### Affected Version(s)
- 4.0.3
- HEAD

### To Reproduce

1. Start any 4-axis Laser project
2. Observe that the '0' for the x-axis is rendered differently than other x-axis labels; it is not outside of the work area and it is not centered on zero.

![image](https://user-images.githubusercontent.com/229922/142867384-4781d014-d075-41db-b4ed-8bbf8ccff6e9.png)

The current behavior is confusing if you are trying to center something around the origin.  At first I would place things centered around the '0' and was disappointed that they appeared to be offset.  I eventually learned to count backwards from the '50' to find the true origin x-axis.  I also think it would be useful to render the origin line slightly thicker than other lines to make it completely obvious where the x-axis origin in placed.

I will try to make a fix and pull-request myself.

Expected behavior

The 0 is rendered like the -50/50 outside of the work area and centered on the line that is zero. 

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: Windows 11 x64
- Printer: Snapmaker A350

</code></pre>

**Comment by maihde** [comment]
I have played around with the rendering in `PrintableArea.js` I personally find this to be the most intuitive display for a user, but understand that it is somewhat subjective.  The zero renders aligned with the x-axis (since the y-axis origin is very obvious in it's location) and the x-axis is render slightly thicker (I also consider doing darker, a different color, or dashed).

![image](https://user-images.githubusercontent.com/229922/143024666-48741b7f-92b1-4c7b-8e83-d75a631e2f26.png)

As a side-effect of the change, 2D projects will have their grid rendered like this:

![image](https://user-images.githubusercontent.com/229922/143025022-20e6dbd7-3b88-40ce-872e-fe6f981fd25d.png)

Which I find to be a small improvement as well, but if there is a desire to not change the 2D rendering in any manner I understand.

I'll wait to see if there is any feedback prior to make a PR.

**Comment by sumibin** [comment]
> 

I think this is a good change. The bold axis can improve both types of projects. The result of zero-aligned to X-axis and Y-axis is not very different for 2D projects, but it can improve four-axis projects.
