### ISSUE TITLE
Bug: v4.1.0 Won't open on Windows 10

### ISSUE THREAD

**Issue by HappyDM1K3Y** [Snapmaker/Luban#1302]
![Error 2021-11-22 6_01_16 PM](https://user-images.githubusercontent.com/88523456/142940053-1245d783-4f4d-4de9-978f-50d1a9f1ffc9.png)

**Comment by jane-rose** [comment]
Caused by electron-updater version, please download this release. https://github.com/Snapmaker/Luban/releases/tag/v4.1.0-beta.1

**Comment by echoeswang** [comment]
Bug: v4.1.0  卡这里不动了   Windows 11
![image](https://user-images.githubusercontent.com/16465480/143236595-d595cfaa-e97c-46d3-8ee4-d6207da0fdd4.png)
