### ISSUE TITLE
Bug: npm install using bad URL for electron

### ISSUE THREAD

**Issue by tgunr** [Snapmaker/Luban#1350]
# 🐞 bug report

### Affected Version(s)
In commit b525665261600b76d2b9341259ef4e600bdef0b9 

### To Reproduce
<pre><code>
npm install
...
> electron@8.5.5 postinstall /Users/davec/Dropbox/3D/Printers/SnapMaker/Luban/node_modules/electron
> node install.js

(node:37826) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v8.5.5/electron-v8.5.5-darwin-arm64.zip
Exception or Error (optional)
</code></pre>

Expected behavior
Clean install

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: macOS Monterey
- Printer: Snapmaker A350

</code></pre>

**Comment by parachvte** [comment]
Outdated. Electron has been upgraded to a newer version.
