### ISSUE TITLE
Bug: Error Loading Certain SVG Files

### ISSUE THREAD

**Issue by dkolepp** [Snapmaker/Luban#1370]
# 🐞 bug report
The 4.x version on Luban does not import some SVG files, which did import in Luban 3.15.

### Affected Version(s)

 The issue is caused by version 4.0, and higher

### Is this a regression? (optional)

 Yes, the previous version of Luban (v3.15.2) did not have this problem.
The error file below loads fine in `v3.15.2`:
![image](https://user-images.githubusercontent.com/10145457/147127847-2386eb0d-fba1-49d5-b178-1d15a5a6b700.png)

### To Reproduce
Here is the problematic file: 
[error.tar.gz](https://github.com/Snapmaker/Luban/files/7764061/error.tar.gz)

1. Download the error file, and untar it (`tar -xzvf error.tar.gz`)
2. Import the `test.svg` file into the Laser area of any `v4.x` of Luban.  This is what happens when I try to load the file:
3. I get the following error message:
![image](https://user-images.githubusercontent.com/10145457/147128139-345700c9-591c-443b-86b7-84002e156d0c.png)
4. Not all SVG files are affected, as I can load a different SVG file:
![image](https://user-images.githubusercontent.com/10145457/147128273-e8d2f555-6897-4422-85db-fc820314be14.png)

Exception or Error (optional)
<pre><code>

</code></pre>

Expected behavior
I have examined this SVG, and I don't see anything that different from the file that works in `v4.x`. The files that does load okay is:
[success.tar.gz](https://github.com/Snapmaker/Luban/files/7764105/success.tar.gz)

## 🌍  Your Environment

**Platform:**
<pre><code>

- Linux (x64, Fedora-based system; RHEL 8.5 [Closest to Fedora 35])
- Printer: Snapmaker A350

</code></pre>

**Comment by sumibin** [comment]
![image](https://user-images.githubusercontent.com/34013829/226610920-68516132-1016-4c48-9005-a91426421f0d.png)
