### ISSUE TITLE
Bug: xxxx in 3d printing

### ISSUE THREAD

**Issue by climatec** [Snapmaker/Luban#1374]
# 🐞 bug report

### Affected Version(s)

 The issue is caused by version x.y.z

### Is this a regression? (optional)

 Yes, the previous version in which this bug was not present was: ....

### To Reproduce
 A clear and concise description of the problem...

Exception or Error (optional)
<pre><code>

</code></pre>

Expected behavior

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: [Windows 10 x64, macOS Big Sur, Ubuntu 20.04, etc]
- Printer: [Snapmaker Original, Snapmaker A150, etc]

</code></pre>

**Comment by climatec** [comment]
Snapmaker, why is this closed without any comment????

**Comment by jane-rose** [comment]
> Snapmaker, why is this closed without any comment????

Sorry, on our end, we don’t see any descriptions, please check if any descriptions are written.

**Comment by climatec** [comment]
Sorry i don’t know why this 1374 are made, the right one is 1375.  I apologise. Just delete this one 1374.
