### ISSUE TITLE
Bug: 3d printing - unable to set nozzle or bed temperature via touch screen

### ISSUE THREAD

**Issue by DirkM20** [Snapmaker/Luban#1384]
Affected Version(s) firmware 1.14.1

The issue is caused by version 1.14.1
Is this a regression? works fine in older firmware

Yes, the previous version in which this bug was not present was: 1.13.2

start print job
change nozzle or bed temp

Exception or Error
nozzle or bed temp does not change

Expected behavior
nozzle or bed temp changes to desired value

setting nozzle or bed temp via octoprint works fine, suppose issue with touch panel to controller communication

**Comment by brprigge** [comment]
Having a similar issue with 1.14.1. None of the linear modules move. Was not an issue on 1.12

**Comment by parachvte** [comment]
@brprigge @DirkM20 Is this issue fixed in latest version?
