### ISSUE TITLE
Bug: Rectangles with rounded corners in SVG result in wrong vector toolpath for laser in Luban 4.1.3

### ISSUE THREAD

**Issue by caerandir** [Snapmaker/Luban#1394]
# 🐞 bug report

Luban seems to ignore rounded rectangle corners in a SVG when calculating the vector toolpath. The display of the imported SVG itself looks right, only the toolpath is wrong. Workaround that works: Convert the rectangle with rounded corners into a path (e.g. in Inkscape). After that, all is correct.

### Affected Version(s)
Luban 4.1.3

### To Reproduce
1. Go to Laser - 3 axis
2. Open attached SVG file - Result: OK, rectangles have rounded corners
![grafik](https://user-images.githubusercontent.com/6073865/148112596-b768f691-454d-4966-9238-4998b970ec91.png)
3. Create Vector toolpath: 
![grafik](https://user-images.githubusercontent.com/6073865/148112700-baf1665a-225f-4e54-adf9-c053cdc19bb3.png)
4. Preview Toolpath - Result wrong - rectangles have no rounded corners
![grafik](https://user-images.githubusercontent.com/6073865/148112820-2861828b-668c-48d2-b33e-196e60f2f1d0.png)

Expected behavior
The toolpath should honor the rounded corners of the two rectangles.

## 🌍  Your Environment

**Platform:**
- Operating System: Windows 10 x64
- Printer: Snapmaker A350
- Luban 4.1.3

Attached ZIP contains:
* RectangleRoundedCorners.svg --> Inkscape created SVG with two rectangles with rounded corners and a bit more
* ConvertedToPath.svg --> Rectangles converted to Pathes. If you load this and run above steps, the result is correct:
![grafik](https://user-images.githubusercontent.com/6073865/148113743-f51e3ccc-76de-4563-a99e-6e651454eefd.png)

[Testfiles.zip](https://github.com/Snapmaker/Luban/files/7809946/Testfiles.zip)

**Comment by theevl** [comment]
I just encountered this problem.
it appears that the preview of the TOOLPATH predicts the "square corners" but the SIMULATION shows rounded corners.
I am using Luban 4.14 on Windows 10

**Comment by jane-rose** [comment]
OK, since we reproduce this on v4.1.4. But we had sloved it on [v4.2.1-beta.1](https://github.com/Snapmaker/Luban/releases/tag/v4.2.1-beta.1). You can use Luban v4.2.1-beta.1 or wait for the official version of the subsequent v4.2.
