### ISSUE TITLE
Bug: In new (4.2) profile migration notification - URL missing/incorrect

### ISSUE THREAD

**Issue by tyeth** [Snapmaker/Luban#1429]
# 🐞 bug report

### Affected Version(s)
4.2 Git a18aa94a5edb98d6f46e08a1a18ec8d2b0dbe992
### Is this a regression? (optional)

NO

### To Reproduce
Have some custom restraction and z-hop settings using a previous version of luban and update to latest commit.
Message shows that Zhop and Retraction are now Material settings (this is brilliant!) and my profiles have been updates/migrated. Click the link to find out more, and another link to view old profile backups. The backups link works, but the first (find out more) link just takes me to Baidu.com.
![image](https://user-images.githubusercontent.com/6692083/150681053-0ac9c203-0478-4d07-bda6-3336b5041cfc.png)

Expected behavior
Click link to find out more and end up at some support page not Baidu.com

## 🌍  Your Environment

**Platform:**
<pre><code>
- Operating System: [Windows 11 x64]
- Printer: [Snapmaker Original, Snapmaker A350]

</code></pre>

**Comment by jane-rose** [comment]
v4.2 is an internal version, this link is not ready yet. It will be ready on v4.2.1.
