### ISSUE TITLE
Bug: Bottom layer height setting does nothing in 3d printing

### ISSUE THREAD

**Issue by HorstBaerbel** [Snapmaker/Luban#1436]
The Bottom layer height setting does not change number of solid bottom layers produced.

### Affected Version(s)
The issue is caused by version 4.1.4

### Is this a regression? (optional)
Have not found existing issues

### To Reproduce
- Set bottom layer height.
- Check number of layers until infill starts
-> Bottom layer height setting does not change infill start

![grafik](https://user-images.githubusercontent.com/1310747/152657137-99205117-e4b0-4950-a917-22a1ac039e92.png)
See above. The infill always starts at layer No. 6, no matter what the bottom layer height is.

Expected behavior
Setting a layer height of 0.4 and a bottom layer height of 0.8 should produce 2 solid layers.

## 🌍  Your Environment

**Platform:**
- Operating System: Ubuntu 20.04
- Printer: Snapmaker 2.0 A350T

**Comment by jane-rose** [comment]
This is not a bug, since there is a parameter called `initial_bottom_layers` that is not exposed. We will accelerate the progress of other parameter exposure.

**Comment by HorstBaerbel** [comment]
Thanks for your answer, but I don't understand. Usually in slicers you can set:
- a fixed number of bottom/top layers
- a minimum bottom/top layer height (aka "Minimum shell thickness" in PrusaSlicer)

"Top Thickness" and "Bottom Thickness" seem to be something else entirely, but then they don't work as described:
![sm_1436](https://user-images.githubusercontent.com/1310747/156988617-bada8c25-3af6-4a1c-9dd0-8ee9629c4326.png)

**Comment by jane-rose** [comment]
> Thanks for your answer, but I don't understand. Usually in slicers you can set:
> 
> * a fixed number of bottom/top layers
> * a minimum bottom/top layer height (aka "Minimum shell thickness" in PrusaSlicer)
> 
> "Top Thickness" and "Bottom Thickness" seem to be something else entirely, but then they don't work as described: ![sm_1436](https://user-images.githubusercontent.com/1310747/156988617-bada8c25-3af6-4a1c-9dd0-8ee9629c4326.png)

Indeed this description is a bit unreasonable, but it is the default description of cura. One more thing, you can maunally change this parameter in this below file. But opening this parameter is in the plan of V4.3.
`
mac:  /Users/{username}/Library/Application Support/snapmaker-luban/Config/printing/fdmprinter.def.json
window:   %appdata%/snapmaker-luban/Config/printing/fdmprinter.def.json 
`

**Comment by hollt693** [comment]
> One more thing, you can maunally change this parameter in this below file. But opening this parameter is in the plan of V4.3.
> 
> `window: %appdata%/snapmaker-luban/Config/printing/fdmprinter.def.json`

How do I change it? I opened the .json file in notepad and changed the "default_parameter" for "initial_bottom_layers" from 6 to 3, and after checking it again just now, that seems to have kept, but I don't see it reflected in the behavior of Luban. Do I need to tell it to re-read the file somehow? I apologize for being so unfamiliar with all of this.
