### ISSUE TITLE
Feature Request: (4-axis) Set laser autofocus and then laser from Luban problem

### ISSUE THREAD

**Issue by skink32** [Snapmaker/Luban#1438]
Hello Snapmaker development team.
I have noticed the following on my Snapmaker 2.0 A350T.
Since I initially had problems with the autofocus function from the control panel and then also from Luban, here what I noticed and should be changed urgently.
Here the example with the Papdose which is contained in the rotation module!

1. I perform an auto-calibration of the laser via the control panel, the panel prompts me to set the working origin.
(In my opinion, this is at the beginning of the material, i.e. opposite the clamping arms of the 4-axis first possibility to engrave on the material). But as I found out, the work origin is not at the beginning of the paper can as I thought, but in the middle of the area of the paper can to be engraved.

2. if I start now over Luban the lasering with the 4-Axis, however as working origin the beginning of the Papdose is taken, thus the foremost point of the Papdose from the 4-Axis module clamping arms seen.

This should be changed, so that with the autocalibration as well as with the following lasering from Luban always the work origin is at the beginning of the papdose. And not once the origin in the middle and once at the beginning.
I assume that this leads many people to drive the laser into the clamping jaws because they forget to reset the working origin in Luban.

Maybe you can include this in one of the next updates of the software it would be very very important!

With kind regards skink32

**Comment by tensile23** [comment]
We revisited this issue. In Luban the user needs to understand that the origin is set to the end of the cylinder. And in autofocus, that is a fixed and cued mark. It is acceptable that they are inconsistent.
