### ISSUE TITLE
Bug: xxxx Translation to German wrong

### ISSUE THREAD

**Issue by FrankBund** [Snapmaker/Luban#1507]
Hello, 
when exiting or switching to another part of the program, I am asked how to proceed with the current project.
- Save (1)
- Cancel (2)
- Do not save (3)
However, in the German version the translation is not correct.

- Speichern (1)
- Abbrechen (2)
- Sparen Sie nicht (3)

To 3 would be here "nicht Speichern" correctly.
"Sparen Sie nicht" would be e.g. a deposit to an account.

Bug is in Version 4.2.2 and 4.2.1
![Bug](https://user-images.githubusercontent.com/82755484/157832080-06acfe52-e3f0-4efe-a411-73344f6b3732.JPG)

**Comment by vibutway** [comment]
Thank you for your feedback, this issue will be fixed in a later version

**Comment by parachvte** [comment]
Has been replaced.
