### ISSUE TITLE
License Violation: Modified Source Code for CuraEngine must be published

### ISSUE THREAD

**Issue by 0ff** [Snapmaker/Luban#1527]
Since https://github.com/Snapmaker/Luban/pull/1060 Luban uses the `snapmaker-luban-engine` instead of CuraEngine. 
This is a direct fork of CuraEngine which, under the license of CuraEngine (https://github.com/Ultimaker/CuraEngine), requires you to publish the modified source code, otherwise you are in violation of the AGPL v3.

This will also solve https://github.com/Snapmaker/Luban/issues/1224.

Please be fair and publish source code if you use open source projects for your products.

**Comment by parachvte** [comment]
Sorry for late response, Pls checkout https://github.com/Snapmaker/LunarSlicer.

It's a new repo derived from CuraEngine, we are migrating our modifications and switching Luban to use the slicer.
