### ISSUE TITLE
Bug: xxxx in 3d printing

### ISSUE THREAD

**Issue by Armanddeforce** [Snapmaker/Luban#1555]
# 🐞 bug report

### Affected Version(s)

 The issue is caused by version x.y.z

### Is this a regression? (optional)

 Yes, the previous version in which this bug was not present was: ....

### To Reproduce
 A clear and concise description of the problem...

Exception or Error (optional)
<pre><code>

</code></pre>

Expected behavior

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: [Windows 10 x64, macOS Big Sur, Ubuntu 20.04, etc]
- Printer: [Snapmaker Original, Snapmaker A150, etc]

</code></pre>
Manual adjustment of hot end temp not working when printing

**Comment by tyeth** [comment]
You need to give more situational information and setup information and project information. i.e. context to your comment.

The issue may be that the printer doesn't respond to commands instantly, it adds them to the current queue (buffer of 16 commands). Some changes or commands will seem instant but are not. The most commonly seen frustration similar to your description is when the machine is executing a M140/M190 and M104/109 which are heat hotend/bed to temp, or heat to temp and wait until reached (ignoring all commands until temperature reached). If you pause the print, it will normally then accept new temperatures once the pause has been executed.
