### ISSUE TITLE
Bug: xxxx in Luban: Laser Cutting

### ISSUE THREAD

**Issue by gilaramirez** [Snapmaker/Luban#1589]
# 🐞 bug report

### Affected Version(s)
 The issue is caused by version 4.2.3

 Unknown

### To Reproduce
1. Open an empty file
2. Click on circle tool
3. Draw an oval
4. Rotate the oval 45 degrees
5. Translate the oval any direction any distance.
6. The rotation of the oval will be reset to zero.

Expected behavior
The shape should retain the rotation after translation.

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: [Windows 10 x64]
- Printer: [Snapmaker A350]

</code></pre>

**Comment by sumibin** [comment]
The issue has been fixed.
