### ISSUE TITLE
Bug: Laser: Fill Line direction ignored

### ISSUE THREAD

**Issue by tyeth** [Snapmaker/Luban#1590]
# 🐞 bug report

### Affected Version(s)
4.3.0

### Is this a regression? 
Yes, there is a bug listed against 3.15 that shows it working in diagonal mode

### To Reproduce
1. Add image and choose vector mode. Create engraving toolpath with Fill, Line mode, Direction:diagonal2, and click generate.
2. Look at the preview, zoom in, the lines are horizontal.

## 🌍  Your Environment

**Platform:**

- Operating System: [Windows 11 x64]
- Printer: [Snapmaker A350 + 10W Laser]

First pointed to from https://www.reddit.com/r/snapmaker/comments/umfsr9/vertical_path_for_laser/
![image](https://user-images.githubusercontent.com/6692083/168657838-c4aa233e-8076-48e9-a08e-969bdf643a25.png)
![image](https://user-images.githubusercontent.com/6692083/168657808-1c2a381f-8f05-45f0-bfb9-8b124c1c3118.png)

**Comment by tyeth** [comment]
[BW_sunset_line_diagonal_0398de10.zip](https://github.com/Snapmaker/Luban/files/8703360/BW_sunset_line_diagonal_0398de10.zip)

**Comment by jane-rose** [comment]
It's abnormal, but I can't reproduce it, maybe you can help us to provide steps for stable reproduction.

**Comment by tyeth** [comment]
No sorry. Still happening in 4.3.2
Try switching engraving material and adjusting modes more. Also I visit the workspace before coming back and adding the model / setting up the engrave.
I just did another and it's only using horizontal. I chose aluminium vector, and then switched from Line to Fill, then change direction in the settings cog.
