### ISSUE TITLE
Bug: In luban with brims

### ISSUE THREAD

**Issue by nfmaas** [Snapmaker/Luban#1614]
When using a brim it will start the supports on layer 1 on top off the brim. But in ares where there is no brim it also starts with thebsupports on layer 1 instead of layer 0.
Photos is made with 4.2.x but 4.3 does the same.
![Layer 0](https://user-images.githubusercontent.com/78142074/172361110-981f0e7a-650c-41d9-9fdb-30ce29c05125.JPG)
![layer 1](https://user-images.githubusercontent.com/78142074/172361117-e06658ce-cd23-4fb8-a2eb-532a7c8d07f4.JPG)

**Comment by jane-rose** [comment]
Could you provide the model to help us solve it?
