### ISSUE TITLE
Bug: camera capture incorrect 10W laser

### ISSUE THREAD

**Issue by Galindorf** [Snapmaker/Luban#1629]
# 🐞 bug report

### Affected Version(s)

 The issue is caused by version 4.3.1

### Is this a regression? (optional)

 Yes, the previous version in which this bug was not present was: the version before this one

### To Reproduce
1. Go to camera capture, image is taken but it is blurry/low quality
2. Align cutting lines to image
3. Generate GCode and preview, looks correct
4. Send to workspace, run via Luban
 A clear and concise description of the problem...
The lines cut far off from my alignment via camera capture. Additionally, when the job is finished the work plate stops all the way in the back.![20220616_191924.jpg](https://user-images.githubusercontent.com/17105217/174200548-a1f2e361-1db5-4300-a383-15d9c2075ac8.jpg)![20220616_191336.jpg](https://user-images.githubusercontent.com)

The camera capture alignment was working so perfectly in the previous version. I restarted Luban and the laser, loaded all my files again but it did not change the behavior.

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: Windows 10
Snapmaker A350, 10W laser

</code></pre>

**Comment by Galindorf** [comment]
![20220616_191336.jpg](https://user-images.githubusercontent.com/17105217/174200826-74fde49d-9872-4852-aff1-bea119e0bbd5.jpg)

**Comment by vibutway** [comment]
From the first picture you provided, the background picture is very obviously skewed; I would like to confirm that you have done the following steps.
1. the camera calibration process is done correctly on the screen side
2. whether the luban control has been calibrated after taking pictures

If the above two steps are not done, it will lead to your printout

**Comment by Galindorf** [comment]
OK, I redid my camera calibration (note: this process was working properly just a couple of weeks ago) and am getting the same kinds of issues. Are the images captured by the camera supposed to be so poor quality? Even the calibration image is so bad I can hardly tell where the lines actually are.
![Screenshot 2022-06-16 235616](https://user-images.githubusercontent.com/17105217/174236815-6dc6fb1a-3299-4072-a532-91fd13258d50.jpg)

If you zoom in on this image and try to align the lines they are almost impossible to see properly. (In addition, attempting to use a mouse to move the corners tiny amounts is extremely frustrating and difficult!)
 
After a second camera calibration on the touch screen and via Luban, I did a test cut where I used Luban's own shape tool on the calibration page that had been cut.  Luban's vision: 
![Screenshot 2022-06-17 010421](https://user-images.githubusercontent.com/17105217/174237205-9c27e999-e2fa-4623-808b-16839c353042.jpg)

**Comment by Galindorf** [comment]
![Screenshot_20220617-010507_Camera.jpg](https://user-images.githubusercontent.com/17105217/174237284-1ea9193e-fd1c-43c7-8ae8-4373ebd1a9aa.jpg)

This is how it cut.

**Comment by vibutway** [comment]
根据您的反馈，我们对您的步骤进行了一遍覆盖：
1. 在屏幕走了一遍摄像校准
2. luban wifi 连接进行摄像捕捉
3. 对照片进行校准，并应用
4. 然后在背景图添加一个矩形进行切割测试

现象如下：添加矩形的位置
![image](https://user-images.githubusercontent.com/82201768/174251462-cef02bb3-9694-4502-8cdd-3d0eebb7f09c.png)

实际切割出来的成品位置
![lADPJvuS0ZFCLHnNBQDNA8A_960_1280](https://user-images.githubusercontent.com/82201768/174251519-c83cc27b-0b0c-4d98-b045-15f15377a098.jpg)

看起来一切正常

希望您确认：
1. 在luban校准后已点击应用按钮
2. 拍完照后，机器上的纸张未被移动过位置

**Comment by vibutway** [comment]
Based on your feedback, we have overridden your steps to.
1. walked through the camera calibration at the screen
2. luban wifi connection for camera capture
3. calibrated the photo and applied
4. then added a rectangle to the background image for cutting test

The phenomenon is as follows: add the location of the rectangle
![image](https://user-images.githubusercontent.com/82201768/174251928-bdc05589-531b-4666-a1e1-4c95542fe367.png)

The actual cut out of the finished position
![lADPJvuS0ZFCLHnNBQDNA8A_960_1280](https://user-images.githubusercontent.com/82201768/174251862-234e6610-c1e3-43d4-8011-0daa0e2f8b5a.jpg)

Everything looks normal

You are expected to confirm that
1. you have clicked the apply button after luban calibration
2. the paper has not been moved from its position on the machine after taking the picture

Translated with www.DeepL.com/Translator (free version)

**Comment by Galindorf** [comment]
1. I did click the 'apply' button for sure
2.  I did not move the paper
3. I did this test before when I first installed the 10w laser to do the calibration and it was perfect

I wish to note that this feature WAS working for me in a previous version of Luban. I was using camera capture to cut letters out of wooden craft sticks, which are only 1.5mm wide.

**Comment by Galindorf** [comment]
I decided to take video just to make sure I was doing everything correctly and got a different problem: camera capture would not respond. Here is the Video:

https://youtu.be/LLdd0h4wqsw

**Comment by Galindorf** [comment]
After restarting the laser and Luban I was able to finish the fresh calibration and cut another test square. The paper was never touched.

Video:
https://youtu.be/HZh7-5eV4EU

**Comment by Galindorf** [comment]
Sorry for all the comments! But I got more information. I decided to try another experiment. I noticed that the square I cut seemed to be smaller than the one I had on the screen. 
I made a new document in CorelDrawx8,  8.5x11" (215.9x279.4mm). Rows of circles. I printed the document actual size on my printer and placed on the laser. I used the same file in SVG to cut out the circles. 

Note: The captured image does not appear to be centered. 
![Screenshot 2022-06-17 131332](https://user-images.githubusercontent.com/17105217/174385121-163f3615-874c-4a81-97d7-217dcec68eb7.jpg)


Test1: 
The file imports looking larger than the captured camera image. 
![Screenshot 2022-06-17 131527](https://user-images.githubusercontent.com/17105217/174385438-89911127-6150-40a0-8342-8e3b079a3010.jpg)
I was unable to get a perfect alignment between the file and the paper. I sized the file until it lined up as much as possible with the camera image. My paper was very straight on the laser bed, I used a ruler to check it. 
![Screenshot 2022-06-17 132935](https://user-images.githubusercontent.com/17105217/174385713-76a6c143-6e44-4f85-a6fd-afba8decedc6.jpg)
The cut was completely off: 
![Screenshot 2022-06-17 134842](https://user-images.githubusercontent.com/17105217/174385995-937a3dfb-f430-4221-ab05-09337bdc4bbb.jpg)

Test 2: 
Placed another printed paper file on the laser bed. This time I did not resize the file in Luban to line it up, I visually centered it as best as I could with the Camera Capture image:
![Screenshot 2022-06-17 134402](https://user-images.githubusercontent.com/17105217/174386138-54b25784-772d-4a9e-84ef-804338f542d1.jpg)

The cut result was MUCH better:
![Screenshot 2022-06-17 134947](https://user-images.githubusercontent.com/17105217/174386168-659bcc00-c3bb-4877-9ce8-aac030bfd3a6.jpg)

Conclusion: the camera capture image is showing the wrong size for the image in Luban.

**Comment by vibutway** [comment]
> After restarting the laser and Luban I was able to finish the fresh calibration and cut another test square. The paper was never touched.
> 
> Video: https://youtu.be/HZh7-5eV4EU

Thank you for your feedback, we will try to reproduce it as soon as possible according to the operation you provide

**Comment by vibutway** [comment]
We have been able to reproduce your feedback problem, the reason is that the height of the executive head has become high, not the default photo height, from the video you sent over, your executive head height should be installed incorrectly
The video you sent shows the installation position as follows.
![image](https://user-images.githubusercontent.com/82201768/174543073-0dd86ae0-5f36-4da4-921a-7281a00566ae.png)

The correct installation position should be
![lADPJvR31GTPpgXNA8DNBQA_1280_960](https://user-images.githubusercontent.com/82201768/174543132-c8fcf4ab-6832-4c4e-8fbc-32df1dc35312.jpg)
![lADPJt8m3Igv6JrNBQDNA8A_960_1280](https://user-images.githubusercontent.com/82201768/174543158-a93e75fc-32c6-4f64-82f2-a45987433e01.jpg)

Please check it, hope to help you

**Comment by Galindorf** [comment]
![20220620_071534.jpg](https://user-images.githubusercontent.com/17105217/174617050-48e92369-fd64-4305-b598-8fc40c300cea.jpg)![20220620_071813.jpg](https://user-images.githubusercontent.com/17105217/174617074-0547f611-e581-4f82-8c96-4b0912a955d6.jpg)

Mine looks right to me. Also, The camera capture WAS working properly before. Better than it ever did before with the 1.6w laser. I used the camera capture to cut some very small items with accuracy.

Is it possible something is wrong with my camera?

**Comment by vibutway** [comment]
I hope you according to the following steps to go through, if the following steps to go through the failure to help you, please contact the aftermarket to change a laser head

1. Please upgrade the screen firmware to the latest version
2. Connect the luban with a serial cable
3. In the console, enter M502 first, then M500
4. reboot the A350 machine
5. Go through the guide process again
6. use luban to do the camera capture

**Comment by Galindorf** [comment]
1. My firmware shows as Snapmaker2_V1.14.2_20220113 and says this is the latest version when prompted to look for an update. Is this correct?
2. I am waiting for a long cable to arrive by mail because my computer and laser cannot reach each other.

**Comment by vibutway** [comment]
Yes, the latest firmware version is Snapmaker2_V1.14.2_20220113 , so you can start from the second step .

**Comment by Galindorf** [comment]
Today I followed steps 2-6. 
My align image was extremely skewed: 
![Crazy Calibration Rectangle](https://user-images.githubusercontent.com/17105217/175697223-07ac1f33-5383-4305-b041-734a844251d0.jpg)

I did the alignment via Luban but the process is extremely difficult and frustrating to do accurately. 
![my calibration](https://user-images.githubusercontent.com/17105217/175697335-1408092d-aabd-4ab6-9623-cb8d57723c2e.jpg)
I took a new image capture of the camera test and I noticed right away that the whole laser bed does not appear in the Image Capture I took: 
![whole bed does not appear to be captured](https://user-images.githubusercontent.com/17105217/175697440-ba3f21ab-ece8-4cd6-8bea-7be5a54ce856.jpg)
However! After trying the cut square it was accurate! I was so happy! This is so much better than what happened before. 
![cut square](https://user-images.githubusercontent.com/17105217/175697575-fe5a7f55-9d3f-40d5-af09-08a4968aa7ed.jpg)

This has not fixed my issue though. I tested another image. 
![warped image 1](https://user-images.githubusercontent.com/17105217/175697655-fa33bb2f-1073-460a-a43a-397b33e1a506.jpg)
You can see the top does not align.  The center does:
![center perfectly aligned](https://user-images.githubusercontent.com/17105217/175697769-9a355441-554b-4641-a2dc-7e148a7768a6.jpg)
(also, the image quality on this camera is really terrible. Really terrible.)

I made a new file that would be easier to test and took this camera capture: 
![warped image 3 full bed capture](https://user-images.githubusercontent.com/17105217/175699446-1e9ad43a-3c96-4d98-bfcb-a45473e012b8.jpg)
As you can see, this time the camera captured the entire laser bed. However, it is still smaller than the exact file I made to cut it. Restarting the machine did not alter this outcome. I aligned the cut file with my own center mark  on the image capture and got this result: 
![image](https://user-images.githubusercontent.com/17105217/175699934-71ff82a7-521e-4bbd-942a-fa1f1fa3bfda.png)

Either my camera is giving a warped view of the laser or the calibration is not working properly? 

I had a different but possibly related weird thing happen, the circles on the Cicada test file did not cut well. Could this all be related to a faulty linear module? 

![image](https://user-images.githubusercontent.com/17105217/175713516-bff0d984-394c-436a-98cb-bd82744d3f16.png)

**Comment by vibutway** [comment]
You can obviously see that your first photo distance is correct, after cutting the distance of the photo again became far away, so it will lead to printing deviations; the following is a luban test package, I hope it can help you.
https://github.com/parachvte/Luban/releases/download/v4.3.2-alpha.2/Snapmaker-Luban-4.3.2-win-x64.exe

**Comment by Galindorf** [comment]
I tried the test package with a couple of files and it seems to be working much better now! I cut a couple of squares that came out properly, then I also redid the camera calibration just to make sure. So far it looks like it's doing well, I will do another test tomorrow. Thank  you so much for all of your help! I will let you know how the test goes tomorrow.

**Comment by ave8tor** [comment]
I too have been running into a similar issue. I noticed that upon selecting 'Add Background' for the initial scan, the laser goes to the normal X/Y centered position above the work surface, however the Z axis is maxed out, causing the work bed image to be smaller than the work bed itself. A subsequent scan causes the Z axis to lower slightly which ‘mostly’ brings the work bed image into the full frame, however the left side of the scan is not quite to the edge of the work bed. Attached are the images for both the initial and subsequent background image captures.
<img width="1904" alt="Initial Scan Option" src="https://user-images.githubusercontent.com/28823978/176185137-6362442c-7f37-4b36-804d-cccc9d38d386.png">
<img width="1904" alt="Initial Background" src="https://user-images.githubusercontent.com/28823978/176185333-f84b6853-7809-4c0c-8344-10ad1144e315.png">
<img width="1904" alt="Second Scan Option" src="https://user-images.githubusercontent.com/28823978/176185413-9c1c74ca-2ebc-43ab-a91b-81ec2cc406b2.png">
<img width="1904" alt="Second Background" src="https://user-images.githubusercontent.com/28823978/176185533-29056f3a-5431-4f2e-a3bc-c8796b9f996a.png">
Although the image looks better in the sense that the work bed covers most of the drawing area, there is still a sliver on the left that is not to the edge. Furthermore, when I took scans of the wood in the appropriate corners, some of the image was cut off, which also indicates that the scanned area is not calibrated to the dimensions of the work bed. I'll try and provide additional images with a future edit.

I then proceeded to test engrave some rectangles in the four corners and the center of the work bed by tracing the lines to match the picture of the scan. The center rectangle was spot on. At each of the corners however, the etched rectangles were set outside (both on the X and Y axis) from each of the rectangles drawn on the test board.

I have re-calibrated the actual camera with the cut paper several times, as well as ensured the image calibration was accurate prior to each image being added as a background. 

The rectangles were placed as closely to their respective corners as I could get, but it did require me to rotate the test board to do so. The arrow in each box represents the font of the work bed. The individual rectangles are labeled UR/UL/LR/LL/CEN for Upper Right/Upper Left/Lower Right/Lower Left/Center.

![Calibration Test](https://user-images.githubusercontent.com/28823978/176185599-02edb77e-3685-4a0a-a59f-e4352fd28aa8.jpg)

The tool head is attached to the correct anchor points, and the calibration on all settings has been performed with no issues. I have the latest firmware and Luban software. I don’t know if there’s something else I’m not doing (or doing wrong), but I find it frustrating that the camera calibration can’t adjust for the work bed itself. Also, why does it take two separate steps to get a valid image and not center the camera at the correct height on the first iteration?

**Comment by Galindorf** [comment]
Suggest: Try printing this file, place on laser bed. Use Camera Capture to take its picture, then load the SVG into Luban and see how it cuts. Then you may see the same issue we are having. (the tiny circle is the exact center of the file)
![calibration template for laser-field squares](https://user-images.githubusercontent.com/17105217/177020270-028b62e5-5533-4502-8419-2fb54839523f.svg)

I am still having issues. The camera quality on this 10w laser head is so bad. I'm starting to regret it. the 1.6w laser took much better photos. Would it be possible to have the camera capture done the same way as the 1.6w laser, where it takes saveral images and then 'stitches' them together? I know it took longer but the camera quality is so bad I can't even tell what I'm trying to cut. :(

**Comment by sumibin** [comment]
There should not be such a large positional deviation in practice. We judge that there is a high probability that it will be a problem with the camera. We will do a verification test on multiple 10W laser heads in these two days.

**Comment by sumibin** [comment]
![Snipaste_2022-07-06_10-57-16](https://user-images.githubusercontent.com/34013829/177458729-2eb27be9-83c8-45be-9490-2af8bffab758.png)
In testing, the largest deviation we encountered was around 1mm.It looks like everyone's end result is worse than this one.
We will schedule a more advanced and precise calibration in Luban, which may lead to a more complex process to achieve a higher accuracy calibration.
@Galindorf There are two possibilities for the "no round" problem. One is that the workpiece may not be clamped, and an engraving test after clamping the workpiece can verify this problem. The other is that the linear module may be faulty, this needs to contact after-sales support.This also brings problems with Camera Capture

**Comment by Stringfamily** [comment]
Hi, I'm running v4.3.2 on MacOS 11.6.8 and have the same camera issues. I know everyone is still having the problem (I assume) but just checking if there is any updates. Thanks!

**Comment by imh1kiko** [comment]
I've decided to chime in as well.
My camera captures have been hella blurry from day 1, and my focus is far from what others get, weirdly enough (31.7mm). Same issues as others have stated -- Lines do not match up, and with perfect aligning, there's weird skewing issue as demonstrated above.

**Comment by tensile23** [comment]
This issue has expired, please reopen an issue if necessary

**Comment by neoscorpio** [comment]
I have the same issue was this ever solved?
