### ISSUE TITLE
Bug: Concentric infill in 3d printing 4.3.2

### ISSUE THREAD

**Issue by tyeth** [Snapmaker/Luban#1634]
### Affected Version(s)
4.3.2

### To Reproduce
1. Select Snapmaker Original machine, choose 3d printing, Insert model, setup a TPU profile or select one if you have one.
2. set walls and top+bottom to 1.2mm, layer 0.2mm, initial 0.28mm. Infill 20% with infill as CONCENCTRIC.
3. Look at layers 6-7 or the infil layers, there was no infil. Changing to 25% had some slanted concentric circles (two lines less than 50% of the way around concentric infill area and more like 2% coverage compared to 0% when selecting 20% concentric infill).
![image](https://user-images.githubusercontent.com/6692083/177009112-8ca98680-a2b2-493b-8640-8129badcb920.png)

4. Change infil to cross and look at same infil layers, they appear reasonable.
![image](https://user-images.githubusercontent.com/6692083/177009070-6b61c659-4464-43b1-b2db-7907c05ba9bd.png)

## 🌍  Your Environment

**Platform:**
- Operating System: [Windows 11 x64]
- Printer: [Snapmaker Original]
[Blindstopfen_washer.zip](https://github.com/Snapmaker/Luban/files/9033327/Blindstopfen_washer.zip)

**Comment by jane-rose** [comment]
@vibutway

**Comment by sumibin** [comment]
![image](https://user-images.githubusercontent.com/34013829/226620822-f3f320f3-2a1c-4f77-bea4-3f455d115c75.png)
The problem still seems to exist in the new engine, keep following up.
