### ISSUE TITLE
Bug: Luban won't load or show materials in 3d printing

### ISSUE THREAD

**Issue by SirLanceabunch** [Snapmaker/Luban#1637]
# 🐞 bug report

### Affected Version(s)

 The issue is caused by multiple versions, 4.3.2, 4.3.1, 4.3.0, 4.2.3, 4.1.4 downloaded them all, same issue on all.

### To Reproduce
1. Open Luban 3D Printing (It won't open)
2. Open Luban laser or CNC
3. File>New>3D Printing
4. Materials drop down is empty, Print settings drop down also empty. (See attached screenshot)
5. Luban will not close, must use task manager to force close.

Expected behavior
Luban should open and provide materials and print styles in the drop downs while allowing changes using the "Settings Gear"

- Operating System: Windows 10 x64
- Printer: Snapmaker A350

![Luban 3DP Error](https://user-images.githubusercontent.com/108643949/177184120-88aa0fa1-7439-43bf-8c1f-43c2848a498f.png)

**Comment by SirLanceabunch** [comment]
![Luban 3DP Error](https://user-images.githubusercontent.com/108643949/177183982-7e61d98d-95c3-4598-8202-71b253c1c6d9.png)

**Comment by vibutway** [comment]
Please follow the steps below, it may help you
  1. Open luban
  2. Shortcut key: Shift + Alt + R

**Comment by SirLanceabunch** [comment]
This worked! I had to recreate my print settings (possibly laser and CNC settings as well) but that's ok
