### ISSUE TITLE
Feature Request: Filament diameter setting in 3D printing

### ISSUE THREAD

**Issue by acanidio** [Snapmaker/Luban#1646]
# Feature Request

### Missing filament diameter setting in the material configuration

Even if in the configuration files there is a setting called "material_diameter" this value is not available to be modified in the UI.

### Describe the solution you'd like?

Introduce the field in the material settings

**Comment by jane-rose** [comment]
In the subsequent v4.4 version, more than 400 parameters have been opened include the "material_diameter". It will be released on early August.

**Comment by reevan8** [comment]
Hi, I see this issue closed as completed but I am using Luban 4.8.1 and I can't find the material diameter settings anywhere. was it added then removed in a later version? or am I just blind?

**Comment by captain118** [comment]
I also do not see it.
