### ISSUE TITLE
Bug: Brim generated first time when selecting user defined Printing Setting in 3d printing

### ISSUE THREAD

**Issue by tim3421** [Snapmaker/Luban#1661]
When I launch Luban 4.3.2, load an STL object, and select one of my created Printing Setting presets, then generate g-code, Luban creates the gcode with a Brim even though the build plate adhesion is set to None.

If I then select a different adhesion type, then select None.  Generate gcode, produces the output with no brim.

# 🐞 bug report

### Affected Version(s)
Luban V4.3.2

### Is this a regression? (optional)

This issue never happened in Luban 3.x

### To Reproduce

Launch Luban 4.3.2, load an STL object, and select a user defined Printing Setting preset, then generate g-code, Luban creates the gcode with a Brim even though the build plate adhesion is set to None.

Expected behavior

None means None.

## 🌍  Your Environment

**Platform:**
MacOS
Luban 4.3.2

![Screen Shot 2022-07-19 at 12 38 53 PM](https://user-images.githubusercontent.com/109625484/179835043-9eb39ce7-9f8e-423b-a34e-78d824656377.png)

**Comment by jane-rose** [comment]
Since we can't reproduce this case. Could u add steps to help us reproduce? One more things, reselect the `build plate adhesion` may solve the issue.
