### ISSUE TITLE
Bug: Bed is OFF - Should be ON in 3d printing v4.4.0

### ISSUE THREAD

**Issue by tyeth** [Snapmaker/Luban#1738]
Not sure how I got this one, but luban 4.4.0 for snapmaker original (it was set to A350 before I reconfigured without closing luban). Selected PETG. Messed with settings, generated gcode, started print via octoprint. 

Problem BED IS OFF.
This is screenshot of gcode header showing desired bed temp and then missing the command from start gcode, and I confirmed in luban that the PETG red has bed set to 70
![image](https://user-images.githubusercontent.com/6692083/193288373-98e751b4-1eeb-436d-bdd5-17a0e2a3f01a.png)

Separate issue, maybe been happening for a few versions: When I went to close luban by using ALT+F4, it offered to save project, I accidentally accepted and the file save dialog appeared, then luban closed itself before I could choose where to save the project.

**Comment by tyeth** [comment]
Reloading Luban and looking back at PETG red for the snapmaker original it now said 40 instead of 70, and I clicked reset and it returned to 70. That doesn't match the previously generated gcode at all.

Generating again with 70 for bed temp it generated with no bed temp instruction. I wonder if it might be an artifact of messing with dual extruder on the A350, as when I goto Material selection page it calls it Left Extruder
![image](https://user-images.githubusercontent.com/6692083/193290451-583e1d07-8509-4c8b-8a1b-ae160025e06d.png)

**Comment by tyeth** [comment]
[Original-Messing-material_and_print_profiles.zip](https://github.com/Snapmaker/Luban/files/9685195/Original-Messing-material_and_print_profiles.zip)
Material profile, Print profile, model, and generated gcodes

**Comment by tyeth** [comment]
I just deleted(moved) my entire roaming profile, so luban setup as new, but same issue when generating code for A350.
[A350_QTPYTop Cover 8mmSlotted_1664552994929.zip](https://github.com/Snapmaker/Luban/files/9685989/A350_QTPYTop.Cover.8mmSlotted_1664552994929.zip)

**Comment by tyeth** [comment]
Installing 4.4.0 in Windows Sandbox on another laptop has generated code for the A350 with bed temperature set:
![image](https://user-images.githubusercontent.com/6692083/193596258-146cf4c8-d39b-497a-83d3-666f26d03729.png)

**Comment by jane-rose** [comment]
Try alt+shift+r(Windows), we will check the upgrad issue for original profile.
