### ISSUE TITLE
Wifi disconnects after 4.2.2 windows only.

### ISSUE THREAD

**Issue by borris345** [Snapmaker/Luban#1757]
Hi,

I have been speaking to support for a few weeks now but to no avail. 

The problem is on windows luban software will disconnect from the machine constantly so the project will stop printing.

It is not a wifi issue my end and is 100% something that has happened after 4.2.2 in the windows build as 4.2.2 works perfectly.

I know it is not a wifi issue as when I use the linux build of 4.4.0 it does not disconnect.

Any version after 4.2.2 on windows constantly disconnects.

They have sent me a new android controller but that has not solved the problem.

I know i can transfer to the machine but i want to use the camera feature.

Operating system: windows 10 fully up to date
CPU: AMD 5900x
Ram: 64gb

**Comment by sumibin** [comment]
If the new version still has this problem please reopen
