### ISSUE TITLE
Bug: Stuck infinitely after homing in 3d printing

### ISSUE THREAD

**Issue by HorstBaerbel** [Snapmaker/Luban#1771]
# 🐞 bug report

### Affected Version(s)
4.4.0

### Is this a regression? (optional)
Yes, regression. No problem in 4.3.2

### To Reproduce
1. Go to workspace
2. Luban wants to home printer, click ok
3. Printer homes itself correctly
-> Homing dialog stuck infinitely. Can't press Ok.

[Video](https://user-images.githubusercontent.com/1310747/204757682-83c53e91-e947-48e4-b28c-55568504df78.webm)

Expected behavior
Homing ends in finite time

## 🌍  Your Environment

**Platform:**
- Operating System: Fedora 36
- Printer: A350T

**Comment by andrewpierson** [comment]
Confirmed on Windows 11, A350.  Worked for me previously, as well on 4.3.2.  Closing the app and restarting it is an annoying workaround.

**Comment by tensile23** [comment]
Should have been fixed in 4.7.2.

**Comment by HorstBaerbel** [comment]
Fixed in 4.7.2
