### ISSUE TITLE
Bug:extruder menu error sign

### ISSUE THREAD

**Issue by Th199403** [Snapmaker/Luban#1838]
there is one character too many. behind the extruder the (&=)

![Unbenannt](https://user-images.githubusercontent.com/121462776/210583504-981c0a51-a1ce-47ae-bee1-87e1eaaba13d.JPG)

**Comment by parachvte** [comment]
We are removing the Extruder Assign overlay on the left tool bar, you should be able to assign extruder(s) on Object List.

**Comment by Th199403** [comment]
okay instead of the extruder layout a button to activate/deactivate the prime tower.
