### ISSUE TITLE
Bed Temperature from material is ignored in Skirt on Luban 4.4.0

### ISSUE THREAD

**Issue by fhorlaville** [Snapmaker/Luban#1849]
Hi,

I created a new material as I have a silk-metal PLA filament which needs a cold to 30º bed temperature.

I used quick create and set the bed temperature to 0-30. This saved properly and displays properly.

Unfortunately, the G-code for the skirt ignores the setting and sets the bed to 70º, completely ignoring the setting.

This is Luban 4.4.0 for Mac.

Thanks

**Platform:**
<pre><code>

- Operating System: macOS Ventura 13.1
- Printer: Snapmaker A250

</code></pre>

**Comment by parachvte** [comment]
Please check if v4.5.0 fix the problem.

**Comment by fhorlaville** [comment]
Fixed in 4.5.0 where all the settings are now available - well done and thank you!
