### ISSUE TITLE
Bug: hangs while homing in 3d printing

### ISSUE THREAD

**Issue by PatonLewis** [Snapmaker/Luban#1853]
# 🐞 bug report

### Affected Version(s)

 The issue is caused by version 4.4.0

### Is this a regression? (optional)

 Not seen in any previous version

### To Reproduce
1. Turn on printer, connect to WiFi
2. Start Luban, create a new 3D print project
3. Export G-code to workspace 
4. Upload G-code to printer
5. Luban prompts that it must home the printer (for uploading? why?!)
6. The printer successfully goes to its home position
7. Luban hangs while waiting for the printer to home, and the modal dialog never goes away
 A clear and concise description of the problem...

Exception or Error (optional)
<pre><code>

</code></pre>

Expected behavior

Expected: app does not hang

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: macOS 12.6.1
- Printer: Snapmaker A350 with original parts, updated firmware

</code></pre>

**Comment by HorstBaerbel** [comment]
Dulicate of #1771
