### ISSUE TITLE
Bug: Luban won't launch "GPU process isn't usable. Goodbye."

### ISSUE THREAD

**Issue by jt55401** [Snapmaker/Luban#1866]
# 🐞 bug report

### Affected Version(s)

4.4.0 / debian installer
ubuntu/popOS 22.04

### Is this a regression? (optional)

Yes - same OS (though, different hardware), version 4.32 worked fine.
Old machine had nvidia 3060 in it (laptop version), with nvidia driver 470 (possibly also newer, I don't remember)
New machine is a desktop with 4090 in it, with nvidia driver 525
(note: GPU works fine in other apps...)

### To Reproduce
Try to launch with shortcut icon - nothing.
Try to launch with command line - I get short log, ending with the below fatal error.

Exception or Error
<pre><code>
[758421:0110/174121.771815:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
</code></pre>

Expected behavior

Luban launches.

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: Ubuntu 22.04 (popOS)
- Printer: Snapmapker A350
</code></pre>

**Comment by parachvte** [comment]
I think it's the same as  https://github.com/Snapmaker/Luban/issues/1830
