### ISSUE TITLE
Bug: Generate VASE EXAMPLE in 4.5.0 - 3d printing

### ISSUE THREAD

**Issue by tyeth** [Snapmaker/Luban#1879]
Tested on two laptops, one with two gpus, both windows 11. Both were upgraded from 4.4, and after loading into 3dp, on the A350, I went back to home to use the Vase example from Case Studies.
I then selected PETG via the Materials button on toolbar, then generated GCode, which stopped at 10%, stalled.
 The second machine I spotted that selecting a material in the window that pops up using the Material button in toolbar doesn't affect the current print settings, so I then clicked the current material name in top right to select PETG print material, then generated GCode, and it also stalled at 10%.

**Comment by parachvte** [comment]
Fixed in #1885 

We will release a patch later this week (v4.5.1).
