### ISSUE TITLE
Bug: line width are ignored in 3d printing (extruder settings do not follow Luban UI settings in print profiles)

### ISSUE THREAD

**Issue by JiriHlavacek** [Snapmaker/Luban#1899]
# 🐞 bug report

### Affected Version(s)
4.5.1 (probably also 4.5.0, but not tested too much)

### To Reproduce
1. Reset all profiles to deafults (delete all profile settings in user appdata folder and/or (re)install to 4.5.1)
2. Setup A250 Dual with 0.8 nozzle on both left and right extruders
3. Set custom line width for skin/wall/infill (other than 0.4mm) for extruders for SM2 A250 printer (dual extruder, but similar behaviour also with single extruder)
3a. Click on Generate GCODE (and Preview if not autogenerated)
3b. Look at settings in .....\AppData\Roaming\snapmaker-luban\Config\printing\active_final.def.json and .....\AppData\Roaming\snapmaker-luban\Config\printing\snapmaker_extruder_0.def.json
4. See error in preview screen or in generated NC code (use any NC code vizualizer)

Exception or Error
Brim/skirt/support line width seems to be ok for any value 0.1 - 1.4

It seems like print settings are set in both extruder and main definition file and overrides each other.

Verified similar line width settings on Cura 5.2.1 with Curaengine slicer and all seems to be OK. 
Printer + extruder Cura settings not copied from Luban, but created from scratch + some modification = mixed Luban Start/End GCODE, no thumbnail, ) 
(as I know Lunar slicer is fork from Curaengine 5.2.x)

Expected behavior
Line width must correspond to settings in Luban, especially for dual extruder machines.

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: [Windows 10 x64
- Printer: Snapmaker 2 A350T, F250

</code></pre>

Sample json content from 
active_final_def.json                 versus                snapmaker_extruder_0.def.json

-------------------------------------------------------------------------

"line_width": {
      "default_value": 0.8
    },
    "wall_line_width": {
      "default_value": 0.1
    },
    "wall_line_width_0": {
      "default_value": 0.2
    },
    "wall_line_width_x": {
      "default_value": 0.6
    },
    "skin_line_width": {
      "default_value": 0.1
    },
    "infill_line_width": {
      "default_value": 1.4
    },
    "skirt_brim_line_width": {
      "default_value": 0.2
    },
    "support_line_width": {
      "default_value": 0.8
    },
    "support_interface_line_width": {
      "default_value": 0.4
    },
    "support_roof_line_width": {
      "default_value": 0.8
    },
    "support_bottom_line_width": {
      "default_value": 0.8
    },
    "prime_tower_line_width": {
      "default_value": 0.8
    },
    "initial_layer_line_width_factor": {
      "default_value": 100
    },

--------------------------------------------------------------------
versus

    "line_width": {
      "default_value": 0.4
    },
    "wall_line_width": {
      "default_value": 0.4
    },
    "wall_line_width_0": {
      "default_value": 0.4
    },
    "wall_line_width_x": {
      "default_value": 0.4
    },
    "skin_line_width": {
      "default_value": 0.4
    },
    "infill_line_width": {
      "default_value": 0.4
    },
    "skirt_brim_line_width": {
      "default_value": 0.2
    },
    "support_line_width": {
      "default_value": 0.8
    },
    "support_interface_line_width": {
      "default_value": 0.4
    },
    "support_roof_line_width": {
      "default_value": 0.8
    },
    "support_bottom_line_width": {
      "default_value": 0.8
    },
    "prime_tower_line_width": {
      "default_value": 0.8
    },

**Comment by JiriHlavacek** [comment]
Temporary "DIRTY" workaround (when nozzle sizes of both extruders are identical or you are using just one extruder):
Remove required line-width from snapmaker_extruder_0.def.json and snapmaker_extruder_1.def.json

Do not have time to find specific place in source code, where definition files are joined/merged together with templates.

**Comment by tensile23** [comment]
This issue should have been fixed in v4.7.2
