### ISSUE TITLE
Feature Request: SM2.0 bed heating finish delay (Alpha)

### ISSUE THREAD

**Issue by parachvte** [Snapmaker/Luban#1930]
The heated bed will deform during the heating process, and waiting a certain amount of time after reaching the target temperature will make heated bed closer to the cold bed state.

![Image](https://user-images.githubusercontent.com/34013829/216566388-7c645f32-b015-4455-9fff-a569c2058d65.png)

Therefore, defining different bed heating finish delays for different print areas can improve the first layer adhesion.

- ≥ 300*300, 10 min
- ≥ 250*250,  8 min
- ≥ 200*200,  5 min
- ≥ 150*150,  2 min
- < 150*150, 0 min

**Comment by sumibin** [comment]
[snapmaker_modify_0.def.zip](https://github.com/Snapmaker/Luban/files/10720445/snapmaker_modify_0.def.zip)

**Comment by parachvte** [comment]
https://github.com/parachvte/Luban/releases/tag/v4.6.0-exp-bed-deform.1
