### ISSUE TITLE
Bug: Changing Nozzle Diameter to 0.6 Crashes Luban

### ISSUE THREAD

**Issue by mmack** [Snapmaker/Luban#1968]
Luban: 4.6.1
Printer: Artisan

Follow this steps, and Luban will crash:

- Change Nozzle Diameter to 0.6 on both Nozzles
- Start the Workbench
- Connect to the printer via wifi

Luban crashes with this message:
Something went wrong. Please reload the app.

Dev Console shows this:
![Capture](https://user-images.githubusercontent.com/100767/219874519-56315eba-059f-4559-bd53-820390aca8fd.PNG)

**Comment by sumibin** [comment]
The Crash problem has been solved, but the sync function still has problems

https://github.com/orgs/Snapmaker/projects/1/views/2?pane=issue&itemId=21044660
