### ISSUE TITLE
Bug: Luban 4.6.1 in 3d printing

### ISSUE THREAD

**Issue by OxygenGS** [Snapmaker/Luban#1982]
Hi,

I Luban 4.6.1 there is a bug that does not save the settings of the materials selected per nozzle. Once you close Luban, and open it again, the settings are back to where they were before. Like this: If I open Luban, it has White in both the nozzles. If I change 1 to black or what ever color, and close Luban and open it back up, it's back to both white again. Very annoying. I did complete reinstall, but it did not fix it. Which makes me believe it's a bug in Luban it selfs.

<img width="264" alt="Screenshot_2" src="https://user-images.githubusercontent.com/37304735/220363797-9554e6ed-d7f4-4db6-8428-d5bd0bbf2930.png">

**Comment by sumibin** [comment]
Fixed in v4.6.2.
