### ISSUE TITLE
Bug: Luban reports error on checking for updates

### ISSUE THREAD

**Issue by colombod** [Snapmaker/Luban#2008]
# 🐞 bug report

### Affected Version(s)

 The issue is caused by version 4.6.3

### Is this a regression? (optional)

 Yes, the previous version in which this bug was not present was: ....

### To Reproduce
1. Go to 'Help'
2. Click on 'Software Update'
3. See error
<img width="410" alt="image" src="https://user-images.githubusercontent.com/375556/221975894-d2e8ea9a-588e-445f-afc9-2b3ca1095676.png">

Exception or Error (optional)
<pre><code>

</code></pre>

Expected behavior

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: Windows 10 x64
- Printer: Snapmaker A350

</code></pre>

**Comment by Andygol** [comment]
I confirm the same issue for Luban 4.6.3 on macOS, M1

**Comment by tensile23** [comment]
This issue has been fixed in v4.7.2
