### ISSUE TITLE
Bug: Missing progress bar for previews

### ISSUE THREAD

**Issue by tensile23** [Snapmaker/Luban#2035]
Reproduction steps

1. Open the project file（Artsian）  [悬浮时钟.zip](https://github.com/Snapmaker/Luban/files/10964328/default.zip)
2. Slice

Missing progress bar for previews
![image](https://user-images.githubusercontent.com/34013829/224901841-c0f19eb0-dfc3-47a8-90a3-f16aab69bc60.png)

**Comment by parachvte** [comment]
Fixed by https://github.com/Snapmaker/Luban/pull/2169
