### ISSUE TITLE
Bug:Laser can't do mulitple passes at same height v4.7.0

### ISSUE THREAD

**Issue by tyeth** [Snapmaker/Luban#2054]
v4.7.0 win11
Draw four boxes on a screen, select all and create toolpath with anodized aluminium vector engraving, change number of passes to 2, automatically z stepdown gets set to 1mm, change it to 0mm, it changes to 0.01, which will affect people who use more than two passes, but to me is minor for this job.
Fix it please

**Comment by parachvte** [comment]
Will be fixed in next minor release (ETA next week).
