### ISSUE TITLE
Feature Request: Firmware update popup

### ISSUE THREAD

**Issue by tensile23** [Snapmaker/Luban#2086]
## Description
When unsupported old firmware is detected, which can cause connection errors or abnormal functions, it prompts the need to upgrade the machine firmware.

## Text
Title
- EN: Connection failure
- CN: Connection failure

Full text
- EN: The machine may be using an older version of firmware or may have other devices connected. To upgrade the firmware, you can check support.snapmaker.com.
- CN: 机器可能使用了过旧版本的固件或已连接其他设备。升级固件的方法可以在 support.snapmaker.com 查询。

**Comment by parachvte** [comment]
key-Workspace/Connection-Connection failed. The machine has been connected to other device.
