### ISSUE TITLE
Bug: Filament Profile Export in 3d printing is not working

### ISSUE THREAD

**Issue by Matt77CHE** [Snapmaker/Luban#2088]
🐞 bug report

V4.7
I tried to export my filament profiles.
Strage is, that I can press the button to save the file in a folder, but it doesn't save it at all. After saving the file, there is no file in this folder.

I tried it on two different computer (Win10 / 11) with luban 4.7 - both the same.

What I did:
3d-Printing
- go to Material
- select a Material
- click on ther three dots
- click on export
- select a folder and pressed save button

Anybody else the same issue?
Matt

**Comment by parachvte** [comment]
It's a known issue and has been fixed in development branch of the repo.

**Comment by tensile23** [comment]
Ready in v4.7.3.
