### ISSUE TITLE
Feature Request: First layer flow parameter

### ISSUE THREAD

**Issue by tensile23** [Snapmaker/Luban#2106]
## Description
For more granular control of first layer flow. to control the elephant foot

![image](https://user-images.githubusercontent.com/34013829/229436614-558aca29-c2db-4b0e-acfd-c336da898f8b.png)

Add location:Material > Initial Layer Optimization

![Image](https://user-images.githubusercontent.com/34013829/231089222-9de6b995-2909-489c-a5ef-b74e6bc3d40e.png)

**Comment by parachvte** [comment]
https://github.com/Snapmaker/Luban/pull/2125

**Comment by tensile23** [comment]
ready in v4.7.3
