### ISSUE TITLE
Bug:  "Generate G-code" unavailable after changing print parameters 

### ISSUE THREAD

**Issue by jmskrz** [Snapmaker/Luban#2109]
"Generate G-Code" not available after changing print parameters in "More settings" section.

Luban 4.7.2 / Windows 11

https://user-images.githubusercontent.com/127803375/229639981-324a8d3a-bd4d-4792-bdfe-10cbb3763cb2.mp4

**Comment by parachvte** [comment]
By Click "Close Preview", you should be able to re-generate G-code.

**Comment by jmskrz** [comment]
Unfortunately, it doesn't work that way..

https://user-images.githubusercontent.com/127803375/229761755-653a0ff6-a85e-4c66-ade5-6e64e0ee1a87.mp4
