### ISSUE TITLE
Improvement: Model error detection performance

### ISSUE THREAD

**Issue by tensile23** [Snapmaker/Luban#2152]
[HULKBUSTER_LeftLeg_1.zip](https://github.com/Snapmaker/Luban/files/11429959/HULKBUSTER_LeftLeg_1.zip)

Imported model stuck at 74.5%

**Comment by tensile23** [comment]
We identified this as a performance issue with model error detection. It will be resolved in a performance-optimized manner.

**Comment by Ubivis** [comment]
No, it just has stopped always at 25% and Luban did not respond anymore, even after several restarts. Since yesterday it suddenly imported fine (no idea why, maybe a windows update?). From my side, everything works fine now :)
