### ISSUE TITLE
In 3d Print > Material selection, there's no way to save changes to the configuration, closing it does not save. Can't even edit print temperature.

### ISSUE THREAD

**Issue by ltmetalman** [Snapmaker/Luban#2157]
# 🐞 bug report

### Affected Version(s)
Luban 4.7.3
3D Print > Select Material
Can't edit print temperature

### Is this a regression? (optional)

Used to work in previous versions, I've created new material profiles before.

Expected behavior

## 🌍  Your Environment

**Platform:**
<pre><code>

Win 10, Luban 4.7.3, Snapmaker A350

</code></pre>

**Comment by tensile23** [comment]
Some previous versions have generated incorrect material configurations that may cause this problem, which you can confirm by modifying the print temperature to a different value. By modifying the print temperature, all temperatures below should be changed correlatively.
![image](https://github.com/Snapmaker/Luban/assets/34013829/3bfbbf09-7886-4465-af04-d9c3c267ea35)
