### ISSUE TITLE
Bug: Laser - with vertical lines on a 360° rotation 10° are missing

### ISSUE THREAD

**Issue by Obicom** [Snapmaker/Luban#2187]
Luban Version 4.8.0 (and before)
Is this a regression? (optional)
Yes

To Reproduce:
Tray to egrave with the 10 Watt lser and rotary module a 360° picture (PNG) on a 23mm (diameter) tube
Picture is exactly 72,3x49mm (23mm diameter x PI = 72,3mm)
Settings: 0,1 lines , fill mode - VERTICAL lines
Connect Luban via Wifi and start the job ...
Luban ask to start from work origin - confirm with YES
Job start working but on the end 10° are missing (ca. 6.4mm are not engraved) - WHY???

If I do exactly the same via Luban and 0,1 lines , fill mode - HORISONTAL lines
Luban ask to start from work origin - confirm with YES
Job start working  and on the end 360° are engraved with exactly the same settings. Only changed from vertical lines to horizontal lines.

🌍 Your Environment
Platform:
Windows 11
Luban 4.8.0 release version (latested)
Snapmaker Artisan with Rotary module and 10W laser

**Comment by tensile23** [comment]
Can you provide us with a Gcode and an image so that we can reproduce your question?

**Comment by tensile23** [comment]
We tried to reproduce your problem on the machine. However, Gcode was able to work well on our machine and the processed part was only a small blank segment.

This issue should not be caused by Luban generating Gcode, please get in touch with technical support for other help (providing this issue will help technical support to troubleshoot the problem.)

Below is the contact information for technical support.
- Technical Support: support@snapmaker.com

**Comment by Obicom** [comment]
@tensile23 : I had the great chance to get a second rotary module (new one) for testing.
What shall I say, exactly the same problem with the second, brand new, rotary module?
What does that mean? We can exclude the rotary module as the reason for this problem.
From my point of view it must be a software( Luban) or Firmware problem. Or what do you think about it?
I attached two new pictures from the new rotary module outcome. The first one shows the 10% gap if I do  verticale engraving on the upper site and below you can see if I do exactly the same with horizontal lines there is no gap.
All round logos are inclined to the right and normal Arial characters look like italic style. (Second picture) This is really a big problem for me.

Please advise, what can I do? In this condition I can't work with the 4-axis mode.Please help.
Thank you in advance.

Best regards, Dirk
![IMG_20230619_221916](https://github.com/Snapmaker/Luban/assets/25134482/129a3c07-e2b9-4cf2-a8ef-de40e6c6db56)
![IMG_20230619_221958](https://github.com/Snapmaker/Luban/assets/25134482/03c4bf5e-77aa-479e-8eaa-f21a632735f6)
![IMG_20230619_222007](https://github.com/Snapmaker/Luban/assets/25134482/e191ad44-cac4-4620-b0cf-13d3f8b5dd01)
