### ISSUE TITLE
BUG: Mesh painting error after colored

### ISSUE THREAD

**Issue by tensile23** [Snapmaker/Luban#2191]
## Reproduction steps 
- Import a model and paint it 
- Using manual support

The support is not generated & the coloring disappears

![Image](https://user-images.githubusercontent.com/34013829/241658835-ed5c7597-62b7-4c66-9a8e-8609722a63ff.png)

**Comment by parachvte** [comment]
![Image](https://github.com/Snapmaker/Luban/assets/3749551/ba83293a-a830-4916-919c-f7f156e3e2e8)
