### ISSUE TITLE
Bug: Objects loose colouring when saving project

### ISSUE THREAD

**Issue by vdborght** [Snapmaker/Luban#2200]
# 🐞 bug report

### Affected Version(s)
Luban 4.8.0

### To Reproduce
1. Import a model
2. Color parts of the model
3. Save the project
4. Close an re-open Luban
5. Open the project from before

Experienced behaviour
Coloring of the model is still present
See screenshots and snap3D project attached

Expected behavior
Coloring is kept

## 🌍  Your Environment

**Platform:**
- Operating System: macOS ventura
- Printer: Snapmaker J1

Colored models before saving the project
<img width="1110" alt="Screenshot 2023-05-29 at 19 35 48" src="https://github.com/Snapmaker/Luban/assets/60184781/4283c2c0-a181-45de-b6d4-a800228adf59">

Loading the same project after closing and re-opening Luban
<img width="600" alt="Screenshot 2023-05-29 at 19 38 34" src="https://github.com/Snapmaker/Luban/assets/60184781/aad66533-7ee2-4374-88c6-fb3ef2485d82">

Project file
[DualColorBug.snap3dp.zip](https://github.com/Snapmaker/Luban/files/11593501/DualColorBug.snap3dp.zip)

**Comment by tkw76** [comment]
I had the same thing happen as well.

**Comment by parachvte** [comment]
Has been fixed in v4.8.1
