### ISSUE TITLE
Bug: App crashs if I want to draw  a line in laser mode

### ISSUE THREAD

**Issue by Obicom** [Snapmaker/Luban#2202]
# 🐞 bug report

### Affected Version(s)
4.8.0

### Is this a regression? (optional)
No

### To Reproduce
1. Go to 'New project'
2. Click on 'Pen' to draw a line

![image](https://github.com/Snapmaker/Luban/assets/25134482/a9950918-c3c9-444f-aa2b-901f770b786d)

Expected behavior
No error message - would like to draw  a line

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: Windows 11
- Printer: Snapmaker Artisn

</code></pre>

**Comment by tensile23** [comment]
We will fix it in the next fix version.

**Comment by ltmetalman** [comment]
I am having this problem still, when can we expect the fix? This seems to have been an issue for a week now. I am just trying to use my laser to cut simple shapes. Right now its a humongous pain to just make a triangle...

**Comment by parachvte** [comment]
@ltmetalman Sorry for bug. A patch version of Luban v4.8.0 will be released this month (v4.8.1).

**Comment by tyeth** [comment]
@parachvte It's treated as a non-issue to assume a customer will roll-back to a working version or not be severely impacted by show-stopper level bugs. That's usually not the case, people just start to resent not being able to use their snapmaker.
 Maybe we (customers) can assume it's a non-issue to release a quick hot-fixed version every time a new show-stopper level bug is introduced in a minor release. Fair enough to not hot-fix everything, but any major regressive bugs should have <7day fix-time

**Comment by ltmetalman** [comment]
Seems to be fixed now... things are much easier now, thank you.

**Comment by parachvte** [comment]
It was an easy fix, sorry for the delay of release (with another laser canvas related issue to be resolved).

**Comment by ltmetalman** [comment]
> @parachvte It's treated as a non-issue to assume a customer will roll-back to a working version or not be severely impacted by show-stopper level bugs. That's usually not the case, people just start to resent not being able to use their snapmaker. Maybe we (customers) can assume it's a non-issue to release a quick hot-fixed version every time a new show-stopper level bug is introduced in a minor release. Fair enough to not hot-fix everything, but any major regressive bugs should have <7day fix-time

It was an easy fix. No worries 'mahn.
