### ISSUE TITLE
Bug: failed to generate code laser engraving for original snapmaker

### ISSUE THREAD

**Issue by foxalite** [Snapmaker/Luban#2223]
# 🐞 bug report

### Affected Version(s)

 The issue is caused by version 4.8.0 Linux version

### Is this a regression? (optional)

 Don't know, Last version i used was snapmkerjs

### To Reproduce
1. Go to 'Quick Start'
2. Click on 'Feather'
3. Click on 'Next'
 Pop-up Failed to generate tool... 
I can't not read the full text, pop-up is going out very too fast
<pre><code>

</code></pre>

Expected behavior

If I try with another printer (A250) code is generating,  slicer is Ok, cnc is OK

Same procedure with Windows version is OK,

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: Mint 21.0
- Printer: Snapmaker Original

</code></pre>

**Comment by parachvte** [comment]
Thanks for the feedback, we updated the starter project for Snapmaker Original.
