### ISSUE TITLE
there is a cylinder that can not be delete

### ISSUE THREAD

**Issue by FranciscoCuan** [Snapmaker/Luban#2255]
in 3d printer When I add a file or change color (dual filament), a cylinder appear and I can not deleted it. When I generate the g code, it generated the cylinder as if I add the shape generating paths.

I have windows 11
64 bites

thank you

![Screenshot 2023-07-10 121029](https://github.com/Snapmaker/Luban/assets/77157995/e266bb28-2a76-4bce-97ea-9c65c73820ba)
![Screenshot 2023-07-10 121057](https://github.com/Snapmaker/Luban/assets/77157995/af322b83-f9d9-4516-9aba-7b639ad88f36)
![Screenshot 2023-07-10 121532](https://github.com/Snapmaker/Luban/assets/77157995/187c181a-d4f1-4c50-aa77-8d59cc087693)

**Comment by igorrynkovoy** [comment]
This cylinder (annoying cylinder) is also don't allow me to generate G-Code.

Printer J1.
Luban 4.8.1
Duplicate mode.

Auto Arrange does not move this cylinder. I have to move it every time manually. CMD + A (Select all) does not work here.


![Screenshot 2023-07-17 at 10 39 07](https://github.com/Snapmaker/Luban/assets/7231376/0a880a87-a998-41a2-b11a-c835a1478c29)

**Comment by tensile23** [comment]
This looks like a problem triggered by the coloring. You can manually clear the coloring status to make the cylinder disappear. ![image](https://github.com/Snapmaker/Luban/assets/34013829/fecafe25-3127-4466-bd8e-3a216a1b6d66)

**Comment by tensile23** [comment]
> in 3d printer When I add a file or change color (dual filament), a cylinder appear and I can not deleted it. When I generate the g code, it generated the cylinder as if I add the shape generating paths.
> 
> I have windows 11 64 bites
> 
> thank you
> 
> ![Screenshot 2023-07-10 121029](https://user-images.githubusercontent.com/77157995/252435720-e266bb28-2a76-4bce-97ea-9c65c73820ba.png) ![Screenshot 2023-07-10 121057](https://user-images.githubusercontent.com/77157995/252435760-af322b83-f9d9-4516-9aba-7b639ad88f36.png) ![Screenshot 2023-07-10 121532](https://user-images.githubusercontent.com/77157995/252437292-187c181a-d4f1-4c50-aa77-8d59cc087693.png)

The cylinder is an erasure tower, you can turn it off in More Settings
![image](https://github.com/Snapmaker/Luban/assets/34013829/58025442-f2ce-4399-916d-02dd062cfeba)
