### ISSUE TITLE
Bug: 10W laser module poor camera quality

### ISSUE THREAD

**Issue by Andy250292** [Snapmaker/Luban#2287]
When I add a background in Luban with the 10W laser module, most of the times I can not use this background because of the very bad quality. I need to guess where the place is I need.

I have a A250 with enclosure and additional lights doesn't solve the problem.

I need a high quality picture from the piece on the work area.
Playing with the image quality also doesn't solve the problem (a description of this function will be nice).

# 🐞 bug report

### Affected Version(s)

 The issue is caused by version (any version)

Expected behavior

I need a high quality picture from the piece on the work area.

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: [Windows 10 x64]
- Printer: [Snapmaker A250, 10W laser module]

</code></pre>

**Comment by tensile23** [comment]
You can try to modify the image quality parameter, the lower the image quality will make the image clearer, but limited by the hardware, the clarity may still not meet your needs. Meanwhile, too large images may cause image transfer failure.
