### ISSUE TITLE
Bug: Enclosure "Door Detection" toggle switch missing

### ISSUE THREAD

**Issue by Rolzad73** [Snapmaker/Luban#2289]
# 🐞 bug report

### Affected Version(s)
4.8.2

### To Reproduce
1. Have Snapmaker 2 with Enclosure
2. Check "Enclosure ui section" (center right of screen)
3. Notice that "LED Strips" and "Exhaust Fan" toggle switches exist, but "Door Detection" is missing

BEFORE (pre-update was Luban 4.7.3?)
![image](https://github.com/Snapmaker/Luban/assets/3611989/b4621d4b-44d7-4259-9c80-0c02eadc709c)

AFTER (Luban 4.8.2)
![image](https://github.com/Snapmaker/Luban/assets/3611989/cec8e1cd-d9ea-4871-8f78-1923bfc23356)

Expected behavior
Door Detection toggle should be available

## 🌍  Your Environment

**Platform:**
- Operating System: Windows 10 x64
- Printer: Snapmaker A350T

</code></pre>

**Comment by Wynand-S** [comment]
I noticed the same in Luban v 4.9.1 - No option to toggle the door detection

**Comment by Rolzad73** [comment]
It looks like it was removed in this commit 407dc7ef56bda4f4632637fa4d7b4c9152b6a98d
Why remove that feature?

**Comment by tensile23** [comment]
On SM2 and Artsian, we removed this feature for security reasons.

**Comment by Rolzad73** [comment]
> On SM2 and Artsian, we removed this feature for security reasons.

What security reason? this isn't a toy made for children.

**Comment by Rolzad73** [comment]
> I noticed the same in Luban v 4.9.1 - No option to toggle the door detection

looks like the have "security" reasons for removing it. Alternatively you can remove the connection for the door detection manually by removing the connection to the main enclosure panel.
