### ISSUE TITLE
Bug: out of filament when priting from Luban over network wont ask for filament change/wont allow resume

### ISSUE THREAD

**Issue by poltpolt** [Snapmaker/Luban#2297]
When I prepare a GCode and select "start on luban" and during the printout I run out of filament there is no message to reload new portion of filament, so after my 70 hours printout I had to throw it away and start again.
When I select "send to device" and start printout n the printer there is a message on the panel to reload filament and I can resume.

I have a very very long printout of 70 hours that is wasted now as I cannot resume 5% to finish.
Is there a way to resume it somehow please?
There has to be the original gcode and status in some file on the printer?

**Comment by tensile23** [comment]
Adding functionality to Luban can complicate online workflows. We have included the ability for "screens to resume print control" in the next SM2 release. This should solve your problem.
