### ISSUE TITLE
Manual Leveling broken

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Luban#245]
The mesh is written in the wrong order. Points 1,5,9 are correct, everything else is mirrored about the X=Y line. I understand this is known, I just wanted it in the list to track it's repair.

**Comment by parachvte** [comment]
The matrix written issue is related to the main controller, I think here should only contain Luban related issues.

**Comment by tonejaco** [comment]
Is the controller project accessible?

**Comment by parachvte** [comment]
No. At least for now.
Or better we get the issues well labeled, I'll create some labels tomorrow.

**Comment by tonejaco** [comment]
Fixed in 1.7
