### ISSUE TITLE
Bug: Rough segments in SVG after processing

### ISSUE THREAD

**Issue by fvlasie** [Snapmaker/Luban#2459]
# 🐞 bug report

The fine curves in an imported SVG become rough and segmented (like a series of straight lines) after generating the preview. The final carving will also have the rough version of the curves.

Before processing curve is smooth:
<img width="655" alt="Screenshot 2024-02-02 at 4 57 36 PM" src="https://github.com/Snapmaker/Luban/assets/33334298/4d30f350-ddd4-46aa-95f9-6c73a9c92e80">

After processing the curve is rough (see the top of the &'s inner curve):
<img width="721" alt="Screenshot 2024-02-02 at 4 57 07 PM" src="https://github.com/Snapmaker/Luban/assets/33334298/fe9bf01e-51bb-419c-8b37-a89cc1127b16">

### Affected Version(s)

 The issue exists in version 4.10.2

### To Reproduce
1. Import SVG file
2. Create Toolpath
3. Generate Preview
4. See the curves in the SVG are segmented into straight lines

Expected behavior
The curves should be smoother in the processed version

## 🌍  Your Environment

**Platform:** 
<pre><code>

- Operating System: MacOS Sonoma 14.2.1
- Printer: Snapmaker A350

</code></pre>

**Comment by xiwai2** [comment]
Hello, this is a problem caused by svg processing，We’ve shared your feedback with our product team, and they’re planning to address it in a future update. Thank you for your patience!
