### ISSUE TITLE
Feature Request: Enable G26

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Luban#246]
G26 lets you print a pattern used to check and validate the leveling mesh.

**Comment by tonejaco** [comment]
Do I read right in the 1.7 source that you can use M49 to toggle the G26 on & off???
Or is it the case that this only works for UBL?
I guess it's still turned off in the Configuration.h

**Comment by parachvte** [comment]
Closing this issue in favor of the issue in the controller repo.
