### ISSUE TITLE
Feature Request: Enable G-code Macros. M810-M819

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Luban#247]
I would like to take advantage of the GCODE Macros. I understand you can do some Macros in the Workspace of Luban, I want to use Macros in a GCode file.

**Comment by tonejaco** [comment]
Can this just be enabled in the Marlin code without requiring other SnapMaker specific changes?

**Comment by parachvte** [comment]
Closing this issue in favor of the new issue in controller repo.
