### ISSUE TITLE
Bug: Flickering area in Dashboard

### ISSUE THREAD

**Issue by thmsnhl** [Snapmaker/Luban#2486]
# 🐞 bug report

### Affected Version(s)
Version 4.13.0 (4.13.0) macOS

### To Reproduce
1. Go to 'Luban' on MacOS (Macbook Pro 13")
2. Stay on the dashboard
3. Observe the container on the lower right hand side
4. See the flickering movement of the contents and the missing font face

Expected behavior
The content of the container should be steady in every screen resolution and the font-face should be "sans-serif" instead of "serif".

## 🌍  Your Environment

**Platform:**
- Machine: 13-inch, M1, 2020
- Operating System: macOS 14.6.1 (23G93)

https://github.com/user-attachments/assets/6223de0b-1d1e-4a81-93b1-fe24c99a638e

**Comment by xiwai2** [comment]
Hello, you can contact our after-sales service to help you solve the problems you have encountered：https://snapmaker.formcrafts.com/support-ticket
