### ISSUE TITLE
G4 is not interruptible.

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Luban#249]
I found that the G4 was not interruptible with the "Stop" button of the Touch Display. The only thing I could do was turn off the power supply. I think the Stop function should be able to interrupt anything and everything, similar to having an emergency stop function.

**Comment by tonejaco** [comment]
Other operations are not uninterruptible too like waiting for the bed or nozzle to heat up.

**Comment by parachvte** [comment]
We are refactoring firmware code, by separating Marlin task and HMI task we will be able to interrupt G-code easily.

**Comment by tonejaco** [comment]
I was thinking that some of the problem lies with the queue in Marlin. I don't know much about it but I was thinking they almost need two queues, one for high priority tasks and one for informational and other type low priority tasks that can be executed any time it is not busy.

**Comment by parachvte** [comment]
Exactly! We did have another queue for commands from Touchscreen, but it's not enough to solve the the problems we faced. We are trying to migrating FreeRTOS into Marlin.

**Comment by tonejaco** [comment]
Super. Just what is needed. Is the Marlin community interested in that too? Seems like they should be.

**Comment by parachvte** [comment]
There were discussions on Marlin over RTOS, I quoted the author's comment here:

> RTOS doesn't appear to add any value to this application with its AVR-centric code architecture. A complete bottom-up rewrite that uses an RTOS would be possible, and that would be the proper approach. But then it would be a completely new firmware.

If there will be a Marlin 3.0, probably they will rebuild on RTOS. Who knows.

**Comment by tonejaco** [comment]
Is this now possible now that RTOS is there?

**Comment by parachvte** [comment]
From firmware 1.9.0, FreeRTOS is there.

**Comment by tonejaco** [comment]
Are you saying that with 1.9.0 the G4 command can now be interrupted? (i.e. "Stopped")?

**Comment by parachvte** [comment]
Hmmmm no. i'm saying we can now facing the staff like Wi-Fi echo issue and interruptions.

**Comment by parachvte** [comment]
Moved to the controller repo.
