### ISSUE TITLE
Bug: Jog height keeps resetting to 1mm in CNC

### ISSUE THREAD

**Issue by dgatwood** [Snapmaker/Luban#2493]
# 🐞 bug report

### Affected Version(s)

4.13.0

### Is this a regression? (optional)

Almost certainly.  No idea how recent, though.

### To Reproduce

1.  Create a CNC project and at least a couple of tool paths.
2. Attempt to change the jog height to something higher than 1mm.
3. Save the change to the tool path.
4. Click on a different tool path.
5. Click back.
6. Reopen the "More" area and observe that the jog height has reset itself to 1mm.

Expected behavior

The jog height should not keep resetting itself to 1mm.

## 🌍  Your Environment

**Platform:**
Mac

- Operating System: macOS Sonoma 14.5
- Printer: A350

**Comment by xiwai2** [comment]
Hello, after setting the parameters for jog height and saving them, you can see in the G code that the setting has been successful. However, there was indeed an error displayed on the Luban interface.We’ve shared your feedback with our product team, and they’re planning to address it in a future update. Thank you for your patience!
