### ISSUE TITLE
Console not echoing thru WiFi connection

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Luban#251]
I understand that this is a known issue, just want to track its repair.
When executing commands thru the console, the results are not echoed back when connected thru WiFi.

**Comment by tonejaco** [comment]
What's the plan on this issue?

**Comment by parachvte** [comment]
This issue is in firmware, also planned after our refactor.

**Comment by tonejaco** [comment]
I just noticed that while connected via WiFi and hitting the "home" button in the "Control" window in Luban echos back the following:
G53
ok
G28
ok
G54
ok

Is that just Luban doing that or is the controller actually echoing what it is suppose to???
If that one works, why don't the others? Maybe just a clue.

**Comment by parachvte** [comment]
The behavior is done by Luban, we switch back to use G54 coordinate system after Homing.

Calling G28 will reset offsets regarding all 3 axes, so a G54 to reload offset is needed.
This is the default behavior of in recent Luban updates.

**Comment by tonejaco** [comment]
Hmm. So I have the 3DP on, why am I seeing G54?

**Comment by tonejaco** [comment]
WHY IS THIS STILL NOT FIXED!!!
I'm disappointed! Please pass this on to the Firmware Team.:frown:

Also, the console echoes back anything you type with an "ok" (FW 1.8)

**Comment by scotthsl** [comment]
![image](https://user-images.githubusercontent.com/18239747/85373391-c6cefe00-b565-11ea-8e70-c5490ebc25e6.png)

Tone, attached is the communication link for Snapmaker2. As you see, all Marlin original output will send to PC1 over UART1. And if you communicate with controller thru WiFi, Gcodes will be wrapped in SM2 protocol, and then send to main controller. Original Gcode output will be send out over UART1. Main contoller just send a ACK with SM2 protocol format to screen, then screen reply to Luban.

**Comment by scotthsl** [comment]
So you can't get original Gcode output thru WiFi. We plan to implement it in next or next two release. Because this function may have more changes.

**Comment by parachvte** [comment]
Moved to the controller repo.
