### ISSUE TITLE
Feature Request: Enable reloading the STL model

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Luban#258]
When you right click on a STL model Cura gives you the option to reload the STL model. I use that often when I use Cura. You can see how the slicing is going and then tweak the STL without having to delete and reload the model which can be time consuming when you have a bunch of STL's in the slicer space.

**Comment by parachvte** [comment]
Do you mean you want to reset the model to "Not previewed" state?
You can do so by dragging the model to move it, or slide the layer bar to the top.

**Comment by tonejaco** [comment]
Reload the STL because it has changed since the time it was loaded.
