### ISSUE TITLE
M114 doesn't work in a GCODE file.

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Luban#262]
When I try a M114 in a GCODE file it doesn't show up on the console. I am connected via USB.
At times it seems to trigger a M105 (temperature report) when executed from the console while a GCODE file was executing. I tried a M400 before the M114 but that didn't help. It seems to only work properly when the controller is sitting idle. Definitely a controller issue unless the command isn't making it through the Touch Screen.

**Comment by tonejaco** [comment]
Learned something. If you do a M400 just before the M114 then it works, at least when executed thru a Luban Macro.

**Comment by parachvte** [comment]
Seems like it's an issue in Luban's communication with the controller, response is sometimes not matched with its request.

**Comment by sumibin** [comment]
The issue seems to have been fixed in v4.7. 
![Snipaste_2023-03-21_17-35-38](https://user-images.githubusercontent.com/34013829/226567972-458c8d9b-e315-403a-9d48-c71cab1f8b02.png)
