### ISSUE TITLE
Snapmaker Luban 3.3.3

### ISSUE THREAD

**Issue by heidnerd** [Snapmaker/Luban#278]
It looks like there is a problem with the user interface when an STL file is imported and sliced.   All layers of fiber are "purple" and identified as "unknown"  moving the slider up and down removes layers of "purple".   Changing the boxes for layers has no effect.

Windows 64 bit version.

![snapmaker 3_3_3 problem](https://user-images.githubusercontent.com/47968854/78849243-c1333480-79c8-11ea-8faa-d4d3556e2b4d.jpg)

**Comment by parachvte** [comment]
Yep what we fixed in https://github.com/Snapmaker/Luban/pull/272 is another issue.

**Comment by parachvte** [comment]
This issue should be fixed in version >= v3.4.2, closing this issue.
