### ISSUE TITLE
Console display artifact

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Luban#283]
When the Console is enlargened to fill from top to bottom the text that is in the lower portion of the Workspace shows thru in the Command input at the bottom. Here's a pic of it:
![Screen Shot 2020-04-10 at 3 48 18 PM](https://user-images.githubusercontent.com/37938299/79050420-1c427280-7be7-11ea-854f-330fc70a8a45.png)
If you're looking at it with a LCD display you may have to look at the screen at an angle to see it. At least that's the case on my MacBook.
 It also affects the region where you can click to activate that area for input.
It could also be related to the "Send Command" text which shows in that region and is supposed to be there.

**Comment by parachvte** [comment]
Related to #254 
The issue should be fix in v3.5.x
