### ISSUE TITLE
Miscommunication to controller

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Luban#284]
Sometimes when I send a command from the console to the controller it echo's back the wrong information. I've had it happen 3 or 4 times now, maybe more. For example, I send a M114 and it echos back "M114 ok" but sends the information from a M105. Here's a screen shot:

![Screen Shot 2020-04-11 at 2 34 54 PM](https://user-images.githubusercontent.com/37938299/79054395-a697d000-7c01-11ea-977d-34e46c97b823.png)

This is with firmware 1.7.1.1 and with USB communication on a Mac with 10.14.2 OS.

**Comment by tonejaco** [comment]
This is still happening with 1.9.0 Firmware. Is this a Luban or Controller issue??

**Comment by parachvte** [comment]
The same issue as https://github.com/Snapmaker/Luban/issues/262
