### ISSUE TITLE
Bug: Override % can go to zero in Touch Screen

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Luban#287]
This is both a Touch Screen Issue and I believe a Luban issue.
If you set the override speed to zero, your print will stop and since it can never reach the next point you'll be stuck. I had this happen to me over the weekend. Had to restart the machine.

I suggest that some minimum non-zero speed be the lower end of the % scale, 5% maybe.

**Comment by parachvte** [comment]
Also should be limited in firmware.
