### ISSUE TITLE
3.4.2 Console anomaly

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Luban#292]
When I switched from an enlarged console panel to expanded and then back to small it doesn't show any content. Switching back to large shows the content again. I did do some other things besides that which could have triggered the problem. I open and closed some of the panels on the right. Enlarged the macro panel. I tried switching to running in a browser but couldn't reproduce the problem. Tried restarting, couldn't reproduce. As I think back, when I first opened 3.4.2 for the first time there was nothing in console window, I tried a couple of "v"'s, nothing, switched to expanded and it showed content so that pane must have initialized wrong or something like that.

**Comment by parachvte** [comment]
I removed a line of initialization terminal in #275, but I didn't find any weird behavior then.
I don't know if it's the problem... we need reproduce somehow

**Comment by tonejaco** [comment]
Going to close unless it happens again.
