### ISSUE TITLE
Feature Request: Copy/Paste or at least Duplicate in Laser or CNC views

### ISSUE THREAD

**Issue by raceimaztion** [Snapmaker/Luban#304]
If you're not sure what settings you're supposed to use for laser engraving or cutting something, the recommended procedure is creating a 2D grid of squares, with each row being a different power level, and each column being a different cutting/engraving speed.

It's more important for laser work than CNC work, but if you're CNCing  something like MDF or even thick layered cardboard, various cutting and bit speeds can be important for a smooth finish.

Anyway, so far, there is no option for duplicating an object, or selecting more than one to make the process faster. You have to import a Vector, select the file, resize it, position it, and then it all again for the next one.

What would be extremely useful under these circumstances is the ability to duplicate an object, at least by right-clicking the object and having a Duplicate option. Even better would be the ability to select multiple objects so you can copy and paste them, making it easier than ever to make a grid, first by building up a row, then duplicating the row as many times as necessary.

**Comment by parachvte** [comment]
https://github.com/Snapmaker/Luban/pull/303 Adds duplicate function on context menu
