### ISSUE TITLE
DXF Arc 360

### ISSUE THREAD

**Issue by WaldoMinny** [Snapmaker/Luban#316]
I've identified that Arcs that start before 360 degrees and go through 360 to end after 0 degrees are not imported.  There are also small arcs that have an issue.
In the attached drawing, there are;
362 Arcs
94 Circles
13 Elipses
2457 Lines
1 Polyline
4 Splines
Attached is also a screenshot with some elements in red that don't load in Luban 3.4.2.  In the Luban screenshot, you can see the arcs not being drawn as well as some other arcs that are not fully drawn in blue.  These are not the ones going through 360, they are merely drawn halfway.

Please feel free to contact me with any additional drawings or tests.

![image](https://user-images.githubusercontent.com/37632029/81342428-87327c80-90b3-11ea-94fb-9f584db7adfd.png)
[Millenium Falcon Rev 17 - Thin Engraving.zip](https://github.com/Snapmaker/Luban/files/4595683/Millenium.Falcon.Rev.17.-.Thin.Engraving.zip)

**Comment by jiantaolovebingbing** [comment]
Yes, I did not consider that the startangle may be bigger than the endangle.I fixed it , you can see the result in the screenshot. But there are a bit problems in some arc, maybe you can help check the startangle and endangle of these 4 'arc'.Thanks!
![image](https://user-images.githubusercontent.com/33253363/81522742-27232b00-937e-11ea-8691-3bfe93b14fdb.png)

**Comment by jiantaolovebingbing** [comment]
Yeah, I did not consider that the startangle may be bigger than the endangle.I fixed it , you can see the result in the screenshot. But there are some extra line  in some arc, maybe you can help check these 4 arc's data. Thanks!
![image](https://user-images.githubusercontent.com/33253363/81558990-3b3c4c00-93c1-11ea-87f4-b63e0346df7c.png)

**Comment by jiantaolovebingbing** [comment]
Yeah, I did not consider that the startangle may be bigger than the endangle.I fixed it , you can see the result in the screenshot. But there are some extra line in some arc, maybe you can help check these 4 arc's data. Thanks!
![image](https://user-images.githubusercontent.com/33253363/81559092-69219080-93c1-11ea-9f05-b1b9b400e9bf.png)

**Comment by jiantaolovebingbing** [comment]
Yeah, I did not consider that the startangle may be bigger than the endangle.I fixed it , you can see the result in the screenshot. Maybe you can check if there are other missing line?
![image](https://user-images.githubusercontent.com/33253363/81561227-72acf780-93c5-11ea-88af-b56d022a75d4.png)

**Comment by WaldoMinny** [comment]
Hi Jiantao

Thank you very much for your assistance.  I think some of the smaller lines
come from other parts of the drawing that are drawn at the wrong location.
How would you like me to test this?  Do you have a compiled version that I
can test?

Regards
Waldo Minny
waldo@minny.com
+27 82 901-2384

**Comment by WaldoMinny** [comment]
> Yeah, I did not consider that the startangle may be bigger than the endangle.I fixed it , you can see the result in the screenshot. Maybe you can check if there are other missing line?
> ![image](https://user-images.githubusercontent.com/33253363/81561227-72acf780-93c5-11ea-88af-b56d022a75d4.png)

Thank you very much

**Comment by jiantaolovebingbing** [comment]
mac or windows?

**Comment by jiantaolovebingbing** [comment]
https://github.com/Snapmaker/Luban/releases/tag/3.5.0-rc.1

**Comment by parachvte** [comment]
Closing this issue as corresponding PR was merged.
