### ISSUE TITLE
Bug: Snpmaker Luban on Debian cannot connect to machine over WiFi

### ISSUE THREAD

**Issue by lichtwellenreiter** [Snapmaker/Luban#339]
For the Versions starting from 3.3.3 I'm unable to connect over WiFi anymore. Removed Wlan Settings  on machine and reconnected. On macOs and Windows it works, I've tested it

**Comment by parachvte** [comment]
@lichtwellenreiter Can you discover the machine over Wi-Fi (in "Connection" widget)?
