### ISSUE TITLE
Win 10 x64 Luban 3.5.0: Starts in mini window

### ISSUE THREAD

**Issue by highcast** [Snapmaker/Luban#341]
Every time I start Luban in Windows 10 x64 (builds 1909 and 2004) the software starts in 2-monitor system at monitor 1 top left corner in a size of just those three buttons: Minimize, maximize, close. You need to always maximize the windows to get started. 

This is a fresh installation of operating system "from the scratch" so not any vendor-specific operating system installation. 

![luban-startup](https://user-images.githubusercontent.com/5370960/83690645-c7751400-a5f9-11ea-9d67-6c6a9afb3662.png)

Edited: typos

**Comment by parachvte** [comment]
It's been fixed in https://github.com/Snapmaker/Luban/pull/335
