### ISSUE TITLE
Scale entry boxes control wrong axes

### ISSUE THREAD

**Issue by wdecook** [Snapmaker/Luban#358]
Edited to better describe the actual problem:
The Y and Z labels next to the scale entry boxes do not match with the colors of the axis indicators shown in the G-code generator. The Y label is blue, but the Y axis is indicated with a green line and box. The Z label is green, but the Z axis is indicated with a blue line and box. The colors of the labels in the Move and Rotate tools appear to be correct (X=red, Y=green, Z=blue).

 See attached images using scaling of a 10mm cube.

![cube_base](https://user-images.githubusercontent.com/36168667/85230188-5bd5c980-b3a3-11ea-8d58-d92485a83fd0.JPG)
![cube_x1000](https://user-images.githubusercontent.com/36168667/85230193-5f695080-b3a3-11ea-9c19-179576bc2067.JPG)
![cube_y1000](https://user-images.githubusercontent.com/36168667/85230196-61cbaa80-b3a3-11ea-902d-95b4a2ff5e9b.JPG)
![cube_z1000](https://user-images.githubusercontent.com/36168667/85230197-63956e00-b3a3-11ea-80d7-6d6b32048dd2.JPG)

**Comment by parachvte** [comment]
Should be fixed now.
Y axis should be green as it was in Move and Rotate.
