### ISSUE TITLE
Bug: Show estimated remaining time when running Gcode directly from Luban

### ISSUE THREAD

**Issue by Scarygami** [Snapmaker/Luban#384]
At the moment this is what you see when starting the Gcode while connected to the machine directly from Luban:
![image](https://user-images.githubusercontent.com/809528/87724204-4fcf0300-c7bb-11ea-8404-1f5a0ad0cf6f.png)

It would be nice to get an estimated time for finish time and remaining time, this could be a simple calculation based on received lines vs. total lines and elapsed time.

**Comment by sumibin** [comment]
This functionality is implemented in the component Job status.
