### ISSUE TITLE
Constrain proportions when scaling

### ISSUE THREAD

**Issue by fvlasie** [Snapmaker/Luban#385]
I just upgraded from Luban 3.5 and I noticed there is no longer a way to constrain proportions when scaling an image. Could we have a "Constrain Proportions" check box or similar feature to make width and height scale together proportionately?

Thank you!

**Comment by jimjworkshop** [comment]
I use this feature all of the time and reverted back to an older version because this feature is missing. I hope it is added back.

**Comment by parachvte** [comment]
https://github.com/Snapmaker/Luban/pull/375 We already have this PR trying to solve the problem.
