### ISSUE TITLE
CNC mode crashing when generating tool path

### ISSUE THREAD

**Issue by fvlasie** [Snapmaker/Luban#386]
I am trying to generate G-code for the CNC function using a depth map. Luban keeps crashing when I press "Preview" to generate  the tool path.

MacOS 10.15.5 Luban 3.7.0.331

Thank you!

**Comment by fvlasie** [comment]
<img width="1112" alt="Screenshot 2020-07-16 at 10 32 40 pm" src="https://user-images.githubusercontent.com/33334298/87752099-7178bc00-c7b4-11ea-9965-ef6c7ccbda02.png">
<img width="1115" alt="Screenshot 2020-07-16 at 10 33 14 pm" src="https://user-images.githubusercontent.com/33334298/87752105-7473ac80-c7b4-11ea-8dbf-40427d2a1eaa.png">

**Comment by fvlasie** [comment]
![DSC_4560_B](https://user-images.githubusercontent.com/33334298/87752169-966d2f00-c7b4-11ea-8c83-49cf65482360.jpg)
<img width="435" alt="Screenshot 2020-07-16 at 10 35 10 pm" src="https://user-images.githubusercontent.com/33334298/87752194-9e2cd380-c7b4-11ea-9a0a-79bac7864f21.png">

**Comment by fvlasie** [comment]
I also tested this on Luban 3.7.0 on Windows — same problem. :(

**Comment by fvlasie** [comment]
The same problem occurs on CentOS 8.

**Comment by fvlasie** [comment]
Also tested with versions 3.5 and 3.6.1—same issue

**Comment by fvlasie** [comment]
Maybe for complex projects we could have the option of generating G-code without the preview?

**Comment by fvlasie** [comment]
The problem still exists with version 3.8.0

**Comment by parachvte** [comment]
Is it still occurs in v3.11.0 or v3.12.0?

**Comment by fvlasie** [comment]
I just tried it in 3.12.2 and the problem is fixed! Yay!
Thank you very much!
谢谢
