### ISSUE TITLE
Bug: After closing Luban, then starting it again, 3dp requests for project recovery

### ISSUE THREAD

**Issue by highcast** [Snapmaker/Luban#395]
Whenever I've finished Gcode for a project and saved it, I close the software from X at the top right corner. 
Then, when next time opening the app and moving to 3D Print module, Luban shows "Project recover: Thje program quit due to an unknown error (reason.) Do you want to recover your last project?"

Luban 3.7.0
Windows 10 x64

**Comment by parachvte** [comment]
Closing the issue since it should be fixed in v3.8.0
