### ISSUE TITLE
Bug: After sending gcode over wifi, wrong work shown in workspace

### ISSUE THREAD

**Issue by highcast** [Snapmaker/Luban#396]
Scenario:
Create a 3d print job, move it to workspace
Send to machine over wifi. Do not start the work. 
Disconnect from Luban. Start the print
Reconnect with Luban to the device
Wrong work is shown on the workspace (some historical work)

Luban 3.7.0
Windows 10 x64

**Comment by highcast** [comment]
This is a regression. Worked in earlier stable versions.

**Comment by endevoir** [comment]
happens to me too, all the time, no exceptions.

**Comment by parachvte** [comment]
Need to check if the issue still occurs in versions >= v3.12.x
