### ISSUE TITLE
Improvement: Make Wifi connection in software more reliable

### ISSUE THREAD

**Issue by highcast** [Snapmaker/Luban#398]
When you leave the connection on, it resets shortly after making the connection. 
Reconnecting does not succeed right away - you need to wait for about 30 seconds until it's available again. 
You will receive an error message of each attempt. 

Tried with modern and stable wifi connection with the wifi box at the same room / other room. Same results. Looks like software issue. 

Happens with all Luban versions 3.3.3+ with two Windows 10 computers

**Comment by parachvte** [comment]
We have #579 and another coming update on Touch Screen firmware to improve this (>= 1.12.0)
