### ISSUE TITLE
3.8.0 does not save custom print profiles

### ISSUE THREAD

**Issue by highcast** [Snapmaker/Luban#402]
Customized print quality profiles do not get saved. When closing the app, those are lost (except if you export them) and you need to do it again upon next program usage. 

Windows platform
Luban 3.8.0

**Comment by parachvte** [comment]
I can not re-produce this.

Check if you are still using the right profile, or if it's the write permission issue of userData folder.

**Comment by highcast** [comment]
@parachvte here's a video record of this issue happening. 

[](https://youtu.be/q9aAZM92cnM)

 or if it's the write permission issue of userData folder.
- What is the specified userdata folder in Windows 10 profile? Where is it?

**Comment by YDKK** [comment]
I have the same issue on Windows platform.
I had upgrade from 3.7.0 to 3.8.0 then all print profiles are lost and Luban entirely no longer save new print profiles.

**Comment by wdecook** [comment]
I have the same issue on Windows 10 after updating to Luban 3.8.0

**Comment by wdecook** [comment]
@parachvte Where is the userData folder? I can't find this directory anywhere in the program file structure.

**Comment by Pflugshaupt** [comment]
I am facing the same issue on multiple windows 10 machines. I started out with 3.8 without prior installation. Material settings do work, but custom print settings are gone on relaunch and it is quite annoying. Reimporting from json also does not work.

**Comment by epic709** [comment]
same issue encountered on Win64 machine. Have double checked all file permissions and nothing works. Can only save print settings to JSON file but unable to load back into Luban. All custom profiles disappear after restarting Luban

**Comment by usefool** [comment]
I have the same issues with Luban 3.8.0 on my Mac. 
1) A printer profile is forgotten after restart of Luban
2) Saving a JSON file works but loading a Json file has no effect

**Comment by usefool** [comment]
Is fixed on Mac with 3.9
