### ISSUE TITLE
cnc "Failed to generate gcode" in outline mode

### ISSUE THREAD

**Issue by t-foster** [Snapmaker/Luban#418]
I found a batman logo svg file, did some conversion stuff to make the background transparent and when I try to generate gcode in outline mode I get a failure.  It generated gcode fine using on the path and fill modes.

See attached file for recreating the issue.
[batmanIssue.zip](https://github.com/Snapmaker/Luban/files/5120209/batmanIssue.zip)

Mac OS, Version 3.8.0.404

**Comment by parachvte** [comment]
Thanks for your feedback! I've put the issue to our current sprint.

**Comment by t-foster** [comment]
were you able to reproduce my error or do you need more info?
