### ISSUE TITLE
Luban 3.9.0 enclosure toggles are the wrong way round

### ISSUE THREAD

**Issue by jgardiner68** [Snapmaker/Luban#464]
If I connect to the Snapmaker 2  using Luban 3.9.0 while it is printing, the enclosure settings are the wrong way round -- off is on and on is off.  On the Android display, they are correct.

![image](https://user-images.githubusercontent.com/45167542/94487692-4e698000-01d9-11eb-87d8-c0d675f18d90.png)

Running Luban 3.9.0 under Ubuntu

**Comment by parachvte** [comment]
We unified copywriting in https://github.com/Snapmaker/Luban/pull/460. Thanks for the feedback, stay tuned for next version.
