### ISSUE TITLE
Image transforms should allow for maintaining aspect ratio

### ISSUE THREAD

**Issue by halr9000** [Snapmaker/Luban#468]
I would like to be able to change the dimensions (size) of an image while maintaining the aspect ratio.

To effect this, you could compute and set the correct other dimension at focus change so as to maintain the current aspect ratio. e.g. if size were 200 x 200 mm, then changing one to 100 would immediately change the other to 100 when hitting tab or mouse event. This would perform a similar function as resizing an object with the mouse while holding down the shift key.

Many apps do this, and there is usually a toggle button indicated with a lock icon. I suggest that the ratio is "locked" by default, as that is the most common expectation in my experience.

Ref screenshot:

![image](https://user-images.githubusercontent.com/18482/95000267-4751c180-058d-11eb-91c7-b28ab030e386.png)

**Comment by sandwyrm** [comment]
@halr9000 which version are you using?  This feature appears to already be available in Luban 3.9.0, see the attached screenshots of CNC and Laser editor screens for reference.

<img width="1072" alt="Screen Shot 2020-10-05 at 11 16 24 AM" src="https://user-images.githubusercontent.com/925698/95098782-198b8a80-06fd-11eb-8839-83f7526ce43a.png">
<img width="1072" alt="Screen Shot 2020-10-05 at 11 16 29 AM" src="https://user-images.githubusercontent.com/925698/95098793-1c867b00-06fd-11eb-8a54-e7f4de7e9a70.png">
<img width="1072" alt="Screen Shot 2020-10-05 at 11 20 19 AM" src="https://user-images.githubusercontent.com/925698/95098800-1f816b80-06fd-11eb-9829-64a2eb7cc573.png">
<img width="1072" alt="Screen Shot 2020-10-05 at 11 20 28 AM" src="https://user-images.githubusercontent.com/925698/95098801-201a0200-06fd-11eb-9d78-06292efe89fd.png">

Are you experiencing this in the latest Luban available?
