### ISSUE TITLE
Luban unable to propertly load CNC/machinist fonts

### ISSUE THREAD

**Issue by sandwyrm** [Snapmaker/Luban#470]
I recently attempted to use a handful of single-line machinist/CNC flavored fonts and discovered Luban produced a few random triangles and almost no recognizable letters with these fonts.  I was unable to locate any working single-line fonts from an assortment of about 15 options.  Luban appears to misread the single-line directions and mutates the font into fitting different geometries which, ultimately, destroys the intended display.  I've attached an example with two CNC fonts and one normal font to demonstrate the difference. 

<img width="2032" alt="Screen Shot 2020-10-04 at 7 04 13 PM" src="https://user-images.githubusercontent.com/925698/95029186-7b53e200-0674-11eb-9337-9659eefe85ac.png">

<img width="2032" alt="Screen Shot 2020-10-04 at 7 04 18 PM" src="https://user-images.githubusercontent.com/925698/95029189-7db63c00-0674-11eb-993f-de18a21d8f9d.png">

Top font is CNC Vector from: http://philing.net/fonts.html

Middle font is standard system Menlo font

Bottom font is Machine Tool Gothic from: http://www.imajeenyus.com/computer/20150110_single_line_fonts/machine_tool_font.zip

Since these types of fonts are usually specifically tailored for machining like CNC and laser engraving, I found it concerning Luban did not support them for their CNC and laser usage.  Some fonts do appear to render in the editor better than others, but the conversion between editor to process tends to mutate into unreadable garbage.

This was produced using Luban 3.9.0 on a Mac.

**Comment by jane-rose** [comment]
It will be working now in 3.12.0. Close now.
