### ISSUE TITLE
Feature request: Add STL support for CNC processing

### ISSUE THREAD

**Issue by gysnst2** [Snapmaker/Luban#479]
I would love to see import of stl into luban. It seams this should be a no brained considering this is also a 3D printer and marketed to the 3D printing community.

**Comment by jane-rose** [comment]
It is on the agenda, thanks.

**Comment by gysnst2** [comment]
In 3.15 when I import an stl into the cnc slicer the orientation is incorrect and their is not a way to fix it.  ![image](https://user-images.githubusercontent.com/32149597/116339724-90749780-a7a3-11eb-921b-bb7ed83dc51f.jpeg)![image](https://user-images.githubusercontent.com/32149597/116339757-9cf8f000-a7a3-11eb-9d55-d91a5001e4b0.jpeg)But if I import that same model into the 3D printer slicer it is imported correctly. ![image](https://user-images.githubusercontent.com/32149597/116339767-a2563a80-a7a3-11eb-878b-e80c54f3ba8d.jpeg)

**Comment by parachvte** [comment]
![image](https://user-images.githubusercontent.com/3749551/116376184-95d4ef00-a842-11eb-9d9b-b470544ace97.png)

You can change "Projection Orientation" of object in the right side panel.
