### ISSUE TITLE
Luban hangs when adding gcode

### ISSUE THREAD

**Issue by halr9000** [Snapmaker/Luban#485]
I have one specific gcode file which was sliced using Cura 4.7.1. When I go to workspace and try to load it using "open gcode file", the display shows an empty white window and nothing else but the menu at the top (file, view, window options).

OS: Linux
Luban 3.9.0

Github will not allow gcode uploads, this link should work: https://drive.google.com/file/d/1KbeQhHZdaGtjiDh6y19gzJY9FUQxRRjj/view?usp=sharing

**Comment by halr9000** [comment]
![Screenshot from 2020-10-18 23-07-08](https://user-images.githubusercontent.com/18482/96397220-08c82380-1197-11eb-8823-d8348d58bf30.png)

**Comment by jane-rose** [comment]
The file you uploaded is not a typical gcode file, please check it!
