### ISSUE TITLE
v3.9.0 Text options lost in the laser/CNC G-code Generator

### ISSUE THREAD

**Issue by TurboPunk** [Snapmaker/Luban#509]
In the laser/CNC G-code Generator text object used to have more options in v3.8.0

Steps to reproduce:
Add a text object in v3.9.0 in the laser/CNC G-code Generator and inspect the properties.
Enter multiple lines of text.

Missing:
- Line height
- Allignment

No longer working:
- Multiline text

Screenshot v3.8.0:
![Screenshot_2020-10-26_14-29-19](https://user-images.githubusercontent.com/1379793/97220502-dd16f000-17cb-11eb-8794-d1e759a1db7d.png)

Screenshot v3.9.0:
![Screenshot_2020-10-26_14-33-58](https://user-images.githubusercontent.com/1379793/97220519-e2743a80-17cb-11eb-95a9-72a41b3afe6d.png)

**Comment by parachvte** [comment]
Yes we rework the text function to support WYSIWYG, so the alignment options were removed temporarily...

While the text is still buggy, we will bring back these options when the text function is stable.

**Comment by sumibin** [comment]
![image](https://user-images.githubusercontent.com/34013829/159872880-4504835f-13d8-40d7-9062-6bf11639bb8c.png)
v4.1.4 solution
