### ISSUE TITLE
Printing Settings missing in 3.10

### ISSUE THREAD

**Issue by golgote** [Snapmaker/Luban#522]
Printing settings are not available anymore in 3.10 (on mac at least)

See: https://forum.snapmaker.com/t/no-printer-settings-in-3-10/10940

**Comment by parachvte** [comment]
Got fixed in v3.10.2 (https://github.com/Snapmaker/Luban/releases/tag/v3.10.2)

**Comment by parachvte** [comment]
Thanks for reporting this. I'm closing the issue.
