### ISSUE TITLE
Feature request: open supported file in Mac OS

### ISSUE THREAD

**Issue by Airmonkdev** [Snapmaker/Luban#559]
Hello,
I'd like to associate Luban app to the supported file extension (.stl, .gcode...) so that if I double click on .stl file (for example) Luban app get opened and I can find the stl file on 3D section.
I've configured Luban on the "Open with:" option for stl file but if I double click on stl file Luban get opened but the stl file is not imported on the app.

Can you please consider to add this feature?

**Comment by jane-rose** [comment]
At present, the file we can double-click to open is only the project file. We will consider that request.

**Comment by Airmonkdev** [comment]
Thanks!
