### ISSUE TITLE
Jog Mode issue on A150

### ISSUE THREAD

**Issue by Airmonkdev** [Snapmaker/Luban#560]
Hello,
I've received my A150 and I've used the Jog Mode to move all the way front and back the bad and see the needed room on my desk... I can't remember the exact procedure I've done but I suppose just playing moving the axis also after the max position cause my Snap to go in a strange irresponsive state. The bad bad was not moving and the coordinates was not correct...

Can you please check the jog mode on the A150?

Thanks and keep up the good work!

**Comment by ldp7** [comment]
Contact support@snapmaker.com and send a video to them.

**Comment by jane-rose** [comment]
Thanks, please concat [support@snapmaker.com](url)
