### ISSUE TITLE
3D Printing G-Code Generator - Wrong structure support

### ISSUE THREAD

**Issue by mr-manuel** [Snapmaker/Luban#561]
Hello,

I have a very strange issue, when enabling the "Generate Support" checkbox under the Printing Settings -> Customize -> Support. Luban 3.11.0 is generating a structure that isn't needed:

![grafik](https://user-images.githubusercontent.com/12592765/99200489-e7faea00-27a5-11eb-911d-830d43e368aa.png) 
![grafik](https://user-images.githubusercontent.com/12592765/99200497-f9dc8d00-27a5-11eb-8504-4330001d2f11.png)

Also here, no structure support should be needed. The gap is 3 mm x 20 mm.

![grafik](https://user-images.githubusercontent.com/12592765/99200725-45dc0180-27a7-11eb-889b-0df33730ac1f.png)

In attachment the STL file (import and rotate 180° on X) and the print settings, to reproduce the issue. [test.zip](https://github.com/Snapmaker/Luban/files/5543383/test.zip)

I found no documentation that this could only a setting issue. Do someone else have this issue?

**Comment by sumibin** [comment]
Between the fact that the slicing engine has gone through several major version updates, this issue has expired.
