### ISSUE TITLE
Bug: Laser Fonts

### ISSUE THREAD

**Issue by Oachkatzale** [Snapmaker/Luban#567]
Dear friends,
unfortunately I noticed with the version 3.10.2 that there is a problem with the G-Code generation of fonts. These look very uneven at the edges. In the details you can see that the individual lines do not start on one line.

Best regards
Lisi
![Laser-fonts](https://user-images.githubusercontent.com/72766269/99444603-b9534f80-291c-11eb-8372-a0803af40b93.jpg)

**Comment by jane-rose** [comment]
A known problem, as far as I know, it may be fixed in version 3.12.0.Thanks
