### ISSUE TITLE
Feature Request: Add 3D model mirror operation

### ISSUE THREAD

**Issue by Airmonkdev** [Snapmaker/Luban#574]
Hello,
is it possible to add the mirror feature on Luban so that we could mirror an stl file? (Cura has this feature!)

Thanks and keep up the great work!

**Comment by Galindorf** [comment]
I am adding another voice for this feature! I am printing a model for a friend, they are purchased from Etsy. The creator only makes one side of an object if it is the same on both sides, which means you have to add the model twice and mirror one of them.

**Comment by parachvte** [comment]
Mirror operation has been added (and will be released onLuban v3.15.0)

https://github.com/Snapmaker/Luban/pull/707

**Comment by sumibin** [comment]
This feature has been implemented
