### ISSUE TITLE
[Feature request] Change Nozzle size

### ISSUE THREAD

**Issue by JohnAllijn** [Snapmaker/Luban#577]
Is it possible to change to nozzle size? 

I would like to print with woodfill, which recommends .5 mm nozzles. It would also reduce print time with large prints without too much loss in quality. 

In the Luban software I cannot find the nozzle settings, only layer height etc.

**Comment by helmut-steiner** [comment]
Any news on this feature?

**Comment by jane-rose** [comment]
Sorry, need to be fully discussed.

**Comment by sumibin** [comment]
This feature has been implemented
