### ISSUE TITLE
v3.12.0: issue loading cnc file

### ISSUE THREAD

**Issue by Airmonkdev** [Snapmaker/Luban#591]
Hello,
I've loaded the attached .cnc file on the pre-release v3.12.0 for Mac OS but it seems nothing has been loaded on workspace.
With the official v3.11.0 everything works fine.

Can you please have a look?
 

[Test_CNC.cnc.zip](https://github.com/Snapmaker/Luban/files/5611884/Test_CNC.cnc.zip)

**Comment by parachvte** [comment]
The issue was introduced by #582 that G-code files with less than 100 lines wound fail to parse.
