### ISSUE TITLE
Bug: Issue saving laser process parameters

### ISSUE THREAD

**Issue by Oachkatzale** [Snapmaker/Luban#593]
unfortunately the laser process parameters are not saved when saving the project. Finding the right process parameters is one of the biggest challenges for most laser projects. It would be very useful if the parameters could be saved with the projects 
 (SNAPLZR).  This could save a lot of work and would 
avoid stupid mistakes.
![snaplzr-save](https://user-images.githubusercontent.com/72766269/100550457-4631cd80-327a-11eb-83c8-3ba10e68e0f0.jpg)
![snaplzr-reopen2](https://user-images.githubusercontent.com/72766269/100550557-12a37300-327b-11eb-97fe-daa6bd7922d3.jpg)

**Comment by jane-rose** [comment]
Sorry, it in the schedule.  Any progress will update in this issue. Thanks! #534

**Comment by snoeberer** [comment]
hello parachvte, do you have an idea in which version this bug will be fixed? maybe an rough schedule?

**Comment by parachvte** [comment]
With v3.15.0, laser parameters should be saved in project.
