### ISSUE TITLE
3.12.2 Vert/horiz flip is ignored when processing laser cut

### ISSUE THREAD

**Issue by PeSme** [Snapmaker/Luban#605]
Repro steps:
- Import SVG
- Use the horizontal or vertical flip buttons (next to rotate angle in Transformation block)
- image gets flipped
- Click on "Process" button to go to the other screen
- image is rendered and gcode is generated for not flipped (original) image

Expected state
 - "wysiwyg", flip flag should be applied in the process screen as well

**Comment by jane-rose** [comment]
Known bug, sorry for that, we will fix it as soon as possible! Thanks.

**Comment by sumibin** [comment]
该问题已被修复
