### ISSUE TITLE
[BUG] Slicer issue, gaps in curves

### ISSUE THREAD

**Issue by MrToast99** [Snapmaker/Luban#609]
Found a bug in slicing an STL file from:

https://www.thingiverse.com/thing:2754146

Also noted in this Snapmaker thread:

https://forum.snapmaker.com/t/luban-not-slicing-some-angles-correctly/12238/2
Luban 3.12.2 has gaps in the curves.

**Comment by sumibin** [comment]
This issue has been fixed after updating the engine.
![image](https://user-images.githubusercontent.com/34013829/226579672-36ce7452-07aa-456e-a1ff-3e817bbd4f11.png)
