### ISSUE TITLE
Feature: M1 native binary for macOS

### ISSUE THREAD

**Issue by rstocks** [Snapmaker/Luban#617]
Please consider compiling with M1 / Arm processor support for macOS.

**Comment by parachvte** [comment]
I haven't read through the issue (https://github.com/electron-userland/electron-builder/issues/5392) about macOS/ARM64.
And we don't have a M1 in hand...

If we add ARM64 build, could you test the package for us?

**Comment by rstocks** [comment]
> If we add ARM64 build, could you test the package for us?

Totally! Point me at 'em :-)

**Comment by SketchWork** [comment]
Same here.  Please point me at a testing version for Apple Silicon (M1).

**Comment by daiku1** [comment]
Also would test Apple m1 processor.  Point me to the testing version

**Comment by aminutolo** [comment]
I know this request is a little older, but I am also happy to test or contribute if provides any benefit. I would also like to see a native build for the ARM64.

**Comment by parachvte** [comment]
Please checkout: https://github.com/parachvte/Luban/releases/tag/v4.5.0-beta.4

There is a test build for ARM64 architecture, [Snapmaker.Luban-4.5.0-beta.4-arm64.testing.dmg](https://github.com/parachvte/Luban/releases/download/v4.5.0-beta.4/Snapmaker.Luban-4.5.0-beta.4-arm64.testing.dmg).

@daiku1 @aminutolo @SketchWork @rstocks
