### ISSUE TITLE
Feature Request: Laser Cutter Text Unicode Support

### ISSUE THREAD

**Issue by Aslan0** [Snapmaker/Luban#620]
The Laser cutter text feature is great, and could expand its versatility massively if unicode characters would be supported.

Quickly finding the right symbol would eliminate having to draw many shapes via .svg file like for example:

✪ ⊕⎊🕀◑㉇➥➽▲ᐁ🢅ΦΩψ

**Comment by parachvte** [comment]
The text uses your system fonts, if the font has glyph related to your character, it will be used.

But we didn't have a default fallback for character that doesn't have its glyph :(
We will complete the text feature later.

**Comment by sumibin** [comment]
Loading fonts that contain these characters will be recognized correctly by Luban. This depends on the font itself.
