### ISSUE TITLE
CNC module does not take into account the bit diameter

### ISSUE THREAD

**Issue by astro-friedel** [Snapmaker/Luban#633]
I was trying out the CNC module, using an svg as the input image. I set the bit diameter to 1.75mm to match the bit I was planning to use and set the carving path to fill, assuming that it would carve out the inside of the image, working up to the boundary lines of the image. When I looked at the finished product I noticed that nearly all of the fine details were gone. From what I can tell the gcode that is generated draws the tool paths so that the center of the bit goes from edge to edge. I expected that the CNC processor would have adjusted the paths so that the edge of the bit went from edge to edge. I verified this behavior by changing the bit size to 3.75mm and comparing the output files. They are identical, but should not be. If I set the CNC up to carve out a 7mm by 7mm square from an object I would expect the finished carve out to be 7mm by 7mm not (7 + bit diameter) mm by (7 + bit diameter)mm.
I am using version 3.12.3 installed via RPM on a Fedora-32 system

**Comment by parachvte** [comment]
Yes the fill didn't add padding to the shape. When we have multiple polygons one in another, it's not obvious that which one needs padding which one needs margin. For the ease of process, Luban only follow the shape paths to fill.

We are reworking on separation of shapes and tool path. Later on we may consider the diameter padding.
