### ISSUE TITLE
Run Boundary is Broken...3.12.3

### ISSUE THREAD

**Issue by emiliodunn92** [Snapmaker/Luban#652]
Run boundary in laser only moves X axis. Worked fine in 3.11.

**Comment by parachvte** [comment]
Could you provide a sample G-code to demonstrate the issue? @emiliodunn92

**Comment by emiliodunn92** [comment]
Any run boundary generated G-code. It would acknowledge the X, and ignore
the Y position.

Oddly enough, it was fixed by swapping my touchscreen.

The only difference to when it worked last and this time was upgrading to
3.12.3 and then attempting to engrave something 304mm tall.

I will try to replicate on the new touchscreen once I finish a few gifts I
am working on!
