### ISSUE TITLE
Problems with snapmaker 2.0 250 connect WIFI

### ISSUE THREAD

**Issue by chrziegler** [Snapmaker/Luban#666]
i have a new snapmaker 2.0 250.
 
I have install "snapmaker-luban-3.12.3" on my pc. If i conect to the machine using WIFI i get only a white screen (see pic). If i reload the machine is not connected und i see my modell. i try this with printer, cnc and laser and i cannot connect to the snapmaker.
 
I try to connect first and then load the model ==> result white screen.
I try to load model first and then connect ==> result white screen.
 
i use the Windows 64 bit verion.
 
Can you help me?

![3d-lw](https://user-images.githubusercontent.com/76680185/103197871-25937c80-48e7-11eb-825c-9a373a2e40e6.JPG)

**Comment by parachvte** [comment]
Save as https://github.com/Snapmaker/Luban/issues/640
