### ISSUE TITLE
Bug: laser text line break

### ISSUE THREAD

**Issue by snoeberer** [Snapmaker/Luban#667]
Bug: unfortunately the line break does not work correctly. 

![line_break_edit](https://user-images.githubusercontent.com/76706526/103247197-58c92080-4966-11eb-9bac-193e251705b0.jpg)
![line_break_process](https://user-images.githubusercontent.com/76706526/103247251-8d3cdc80-4966-11eb-91e4-31a704ecf74a.jpg)

I think with version 3.8 it was still possible to insert a line break correctly. it would be nice if this bug could be fixed.

**Comment by sumibin** [comment]
v4.7 has implemented an alternative font scheme which includes most of the characters.
