### ISSUE TITLE
Actual printing and progress not in sync.

### ISSUE THREAD

**Issue by splt7190** [Snapmaker/Luban#672]
I connect my macbook to my Snapmaker Original printer to do printing.  Since updating to 3.9.0 and 3.12.3, sometimes the progress on Luban freezes while the printing is going on and most of the time, the progress is ahead of the actual printing.  This affected my print works.  I am not able to control when I want to pause the print.  When it freezes, it burned my heat bed sticker.

**Comment by sumibin** [comment]
Luban v4.1.4 Feature,Sync with Screen Job.
