### ISSUE TITLE
Luban V3.13.0 Image size ratio is locked

### ISSUE THREAD

**Issue by sdj544** [Snapmaker/Luban#683]
Unable to use the 'unlock' so that I can resize an image and change it's aspect ratio. This is in both laser and cnc.

**Comment by jane-rose** [comment]
Known bug.

**Comment by sdj544** [comment]
Still exists in 3.13.1

**Comment by parachvte** [comment]
> Still exists in 3.13.1

We are working on it, planned in v3.15.0.

**Comment by jumed29** [comment]
Why is it still not working?

**Comment by parachvte** [comment]
> Why is it still not working?

It's fixed. By clicking the "Lock" icon on size, you can change image size freely.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/3749551/212618174-3aea859c-5360-4b60-aec2-107109cb87f4.png">

I'm closing this issue.
