### ISSUE TITLE
gyp err: rebuild failed

### ISSUE THREAD

**Issue by lpg-kobe** [Snapmaker/Luban#715]
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: getaddrinfo EAI_AGAIN electronjs.org electronjs.org:443
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\p_installed\\node.js\\node.exe" "E:\\project\\wemake\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.18" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd E:\project\wemake\dist\Snapmakerjs\node_modules\@serialport\bindings
gyp ERR! node -v v10.23.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1

when i pull code of branch stable and run build & run build:win-x64 in  version 10.23.1 of node.js it always cause this error

**Comment by parachvte** [comment]
`stack Error: getaddrinfo EAI_AGAIN electronjs.org electronjs.org:443`

Seems like it's a network issue?
