### ISSUE TITLE
Not able to change dwell on multiple greyscale images

### ISSUE THREAD

**Issue by sdj544** [Snapmaker/Luban#734]
Luban 3.13.1
If I duplicate an image in laser the dwell setting box disappears when trying to change settings.
If I import the image again, it works.

<img width="931" alt="Screen Shot 2021-01-30 at 1 17 57 PM" src="https://user-images.githubusercontent.com/68141039/106368369-e39e9180-62fd-11eb-9512-d06ec0982ff7.png">
<img width="934" alt="Screen Shot 2021-01-30 at 1 18 07 PM" src="https://user-images.githubusercontent.com/68141039/106368372-e5685500-62fd-11eb-919c-c3a7134c9928.png">

**Comment by sumibin** [comment]
This feature has been implemented in the new version.(Different objects can use the same Toolpath)
