### ISSUE TITLE
[FEATURE] Undo/Redo shortcut for laser-engraving luban.

### ISSUE THREAD

**Issue by pauserratgutierrez** [Snapmaker/Luban#745]
Hi, I think it will be amazing to have such a feature (control + z and control + y) to go forward and backward into editing.

**Comment by parachvte** [comment]
We used to have Undo/Redo for "Edit" page, some code broke it. We will add the feature back when Luban is more stable.

**Comment by sumibin** [comment]
This feature has been released.
