### ISSUE TITLE
[SUGGESTION] Luban text & font ideas

### ISSUE THREAD

**Issue by pauserratgutierrez** [Snapmaker/Luban#749]
It's a mess everytime I need to search for a font and I need to scroll to find it. We need a search imput to search fonts!

It will be cool to have font weight for every font. (thin, light, normal, bold, extrabold) or better to have an imput to set weight number :)

It will be an amazing feature to see a default sample of the text that we might select. When we click to change the font, the dropdown could have each title of font with the desired font aplied to see how it is.

**Comment by parachvte** [comment]
1. search feature is pending.
2. not all font has weighted glyph (though we didn't deal with it); and we didn't really handle fallback glygh (missing glygh will result in a white block).
3. We want it, but haven't scheduled it too.

**Comment by paauserrat** [comment]
2. Okey, so not all the fonts can have weights. What about having an imput that appears only when the font has the ability to change weight?

**Comment by sumibin** [comment]
These features have already been released.
