### ISSUE TITLE
[BUG] Luban laser text cut after process

### ISSUE THREAD

**Issue by pauserratgutierrez** [Snapmaker/Luban#751]
When using the Laser module and inserting text with the native luban text editor and clicking full density and using any value, the text gets cut when processing. The laser also cuts it.
Editing text
![editor](https://user-images.githubusercontent.com/73240206/106913564-69f31300-6704-11eb-874f-44e51f3c81ab.jpg)
Processing text (error, cut)
![process](https://user-images.githubusercontent.com/73240206/106913617-77100200-6704-11eb-868a-26ef75244c09.jpg)

**Comment by parachvte** [comment]
This should be fixed by https://github.com/Snapmaker/Luban/pull/739
