### ISSUE TITLE
3d printing more g-code options

### ISSUE THREAD

**Issue by pauserratgutierrez** [Snapmaker/Luban#754]
The options Luban brings to us when 3d printing are very limited. For example prusaslicer (slicer of prusa machines) has a lot of options like pattern angle, cooling filament settings like fan speed, disable fan for first layers... option to set layers of the 3d print where we want the printer to stop so we can change the filament color and then the printer will continue...

**Comment by sumibin** [comment]
Currently Luban has quite a few parameters open. This issue will be closed.
