### ISSUE TITLE
In cnc & laser tabs the 'reset position' icon doesn't work

### ISSUE THREAD

**Issue by sdj544** [Snapmaker/Luban#770]
In cnc & laser tabs the 'reset position' icon doesn't work.
The magnifying glass icons work to zoom in & out, but when you try to zoom out to the starting position with the reset icon it doesn't do anything.
<img width="87" alt="Screen Shot 2021-02-14 at 10 50 40 AM" src="https://user-images.githubusercontent.com/68141039/107886152-f8108b80-6eb2-11eb-9ee5-dbe2cc9f8e73.png">

**Comment by jane-rose** [comment]
Known bug, fixed on version 3.14.0
