### ISSUE TITLE
Undo doesn't do anything?

### ISSUE THREAD

**Issue by Galindorf** [Snapmaker/Luban#779]
I am new to this program so I am not sure how much is user error, and how much is program error. I am having lots of difficulties with Luban, but one thing I noticed is that the Undo doesn't seem to do anything, at all. If I delete something by accident and choose "undo" nothing happens. If I move an object by accident, undo does not fix it. Am I the only one? 

Luban 3.13.1
Windows 10 on SurfaceBook original

**Comment by Wynand-S** [comment]
I concur - accidentally delete the wrong model, can't undo.
Move the model but need it back exactly on the previous spot, can't undo the move.

**Comment by jane-rose** [comment]
Since we can't reproduce it ? Could you please tell me more information of it so that we can troubleshoot it? How about the version and platform?
