### ISSUE TITLE
Bug in CNC path

### ISSUE THREAD

**Issue by marsiancba** [Snapmaker/Luban#806]
This is a problem I encouter quite often when generating CNC toolpath:

![image](https://user-images.githubusercontent.com/5137942/109548191-3d90a380-7ac4-11eb-8d1b-e227cdd29790.png)

Seems that sometimes when tool goes over a ridge, it "forgets" to drop down to correct depth after the ridge.

(Luban 3.13.1)

**Comment by jane-rose** [comment]
Could you provide your project file so that we can understand exactly what your problem describes. 
As for how to export the project file, click the menu at the top one by one, 'File' -> 'save as'.

**Comment by marsiancba** [comment]
@jane-rose 

https://www.dropbox.com/s/ndlfdc2tji8u80n/bug_cnc.snapcnc?dl=0

![image](https://user-images.githubusercontent.com/5137942/110300711-1ae41a80-7fef-11eb-90fd-f61c8c1b9fa9.png)

**Comment by jane-rose** [comment]
Ok, we can reproduce it. we will repair it as soon as possible. Thanks for your reply.

**Comment by parachvte** [comment]
This issue has been fixed in https://github.com/Snapmaker/Luban/pull/836 and released in Luban versions >= 3.14.0.
