### ISSUE TITLE
Confusing laser G-code generator UI config state 

### ISSUE THREAD

**Issue by anyu** [Snapmaker/Luban#829]
In the Configurations > Working Parameters panel of the Laser G-code generator, there is a state for the `Multi-pass` and `Fixed Power` options in which it's a checked/greyed out checkbox. 

<img width="345" alt="disabled-state" src="https://user-images.githubusercontent.com/1009227/110230235-905fc600-7edd-11eb-95a6-f5c460103cd3.png">

The 'checked'-ness of this is confusing, because it makes it seem like the options are either _selected and unchangeable_ or _unselected and unchangeable_, when in reality, these options are _unselected and changeable_. This would be better represented by unchecked checkboxes.

**Comment by jane-rose** [comment]
Thanks, it's reasonable.
