### ISSUE TITLE
Error empty filament

### ISSUE THREAD

**Issue by baron-digit** [Snapmaker/Luban#850]
I updated my snapmaker 2.0 today to the current Version for Windows 10.

I printed a job for around 6h directly from an USB file and received around 40 false filament errors. Not sure if something changed with the new firmware, but quite annoying...

**Comment by jane-rose** [comment]
Could you send your error info? Just 'empty filament'. 
One more thing, Could you provide your project file so that we can reproduce the issue.
As for how to export the project file, click the menu at the top one by one, 'File' -> 'save as'.

**Comment by baron-digit** [comment]
The last time I started the print directly via USB, but today I tried another file directly from Luban and have the same error (409). It ended up that I wasn't able to restart the print, although loading the filament immediately extruded the filament.... 

it was just a simple STL-file

[funnel.zip](https://github.com/Snapmaker/Luban/files/6134487/funnel.zip)

**Comment by sumibin** [comment]
If this problem still exists in the new version, please reopen it.
