### ISSUE TITLE
Door Detection On / Off is switched in 3.13.1

### ISSUE THREAD

**Issue by amv5012** [Snapmaker/Luban#870]
If I turn on Door Detection, it acts like its off. I made the mistake of thinking the laser wasn't running while Door detection was on. 
and if its Off, its actually on. 
![image](https://user-images.githubusercontent.com/35547116/110986787-55b9bb80-832b-11eb-9290-566a5c1a627b.png)

**Comment by jane-rose** [comment]
Could you tell us what version of the firmware you are using?

**Comment by amv5012** [comment]
Hi Jane,

This is what I see on my screen, see attached

**Comment by amv5012** [comment]
same issue in luban 3.14.0

**Comment by amv5012** [comment]
![image](https://user-images.githubusercontent.com/35547116/111674026-2ef2fd80-87e1-11eb-9dc4-299520bc11b6.png)

**Comment by amv5012** [comment]
![162178942_859152651299377_5254413571194895296_n](https://user-images.githubusercontent.com/35547116/111674125-4cc06280-87e1-11eb-93c4-cf2ca45fdefa.jpg)

**Comment by amv5012** [comment]
seems to be fixed in 3.15.0
