### ISSUE TITLE
Feature Request: Add PETG preset

### ISSUE THREAD

**Issue by mr-manuel** [Snapmaker/Luban#887]
# 🐞 feature request

I'm missing a preset for material and printing settings für PETG material. I bought a Snapmaker 2.0 and PETG filament from your shop but the PETG presets are missing in Luban.

I found a post in the forum also discussing about it: https://forum.snapmaker.com/t/petg-printing-profile/5726/19

Can you please add such a preset?

**Comment by WillBeebe** [comment]
I added the settings from the forum [here](https://github.com/Snapmaker/Luban/pull/893).

**Comment by jane-rose** [comment]
Thanks.But our test of petg's printing profile is in progress, I may wait until the test is over before adding it.

**Comment by WillBeebe** [comment]
No problem, just trying to help 🙏

**Comment by parachvte** [comment]
PETG profile is available in Luban v4.0.0.
