### ISSUE TITLE
Bug: Adding more than six text objects fails or takes very long

### ISSUE THREAD

**Issue by deimi** [Snapmaker/Luban#912]
# 🐞 bug report

### Affected Version(s)

 The issue is caused by version 3.14.0 and 3.15.0

### Is this a regression? (optional)

 Not sure, but i think it was working with 3.13

### To Reproduce
When adding more than six text objects to a cnc/laser project, it fails to add the object. See the attached GIF.  
![text_error](https://user-images.githubusercontent.com/8256985/113784503-d9ea3d80-9735-11eb-970f-b27f83ec6d56.gif)  

I also checked for the api responses with the developer tool. There I can see that I don't get a response for my request of adding a text object.
![image](https://user-images.githubusercontent.com/8256985/113784492-d3f45c80-9735-11eb-8dba-92c4e7234efd.png)  

Sometimes the response comes after very long time. In this example after 59sec!!!!
![image](https://user-images.githubusercontent.com/8256985/113785040-a8be3d00-9736-11eb-8dff-0710d36198f3.png)

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: Ubuntu 20.04
- Printer: Snapmaker A350

</code></pre>

**Comment by deimi** [comment]
This problem also occurs when you not just add more then six text object in a row, but also edit them in between. This means that when I working on a project with several text object or when I delete one and add a new instead, the problem arises as well after about six objects.

**Comment by deimi** [comment]
@parachvte @jane-rose any clue/idea?

**Comment by jane-rose** [comment]
On my macbook, there is indeed a lag of more than 10 seconds before rendering.

**Comment by deimi** [comment]
Same behavior in 3.15.0

**Comment by parachvte** [comment]
@deimi 
We were unable to reproduce the behavior on Windows (both versions).
We'll retry on Ubuntu...
