### ISSUE TITLE
Bug: CNC - Scale not correct for DXF files. 

### ISSUE THREAD

**Issue by EHoglid** [Snapmaker/Luban#943]
When importing DXF file to the CNC view, the scale is all wrong. 
Default should be 1:1,it is really hard to get the correct dimensions when the only way is to resize it inside Luban.

**Comment by jane-rose** [comment]
Sorry for that, same issue with #502. And it should be fixed in version v3.15.0.(Expected to be released this week）
Alternatively, you can use a [test package.]( https://github.com/parachvte/Luban/releases)(might be some bugs)

**Comment by parachvte** [comment]
Please check if the issue still occurs in v3.15.0.

I'm closing this issue for now.
