### ISSUE TITLE
Bug: Structure support created in mid air (3D Printing G-Code Generator)

### ISSUE THREAD

**Issue by mr-manuel** [Snapmaker/Luban#945]
# 🐞 bug report

The G-Code generator creates a support structure in mid air that is nowhere attached:
![grafik](https://user-images.githubusercontent.com/12592765/115153775-e9438200-a077-11eb-9301-ad452d5a733b.png)

### Affected Version(s)

 The issue is caused by version 3.14.0

### To Reproduce
1. Import the STL file [test.zip](https://github.com/Snapmaker/Luban/files/6331765/test.zip)
2. Import profile from the zip or use this Support settings:
![grafik](https://user-images.githubusercontent.com/12592765/115153891-6e2e9b80-a078-11eb-90d2-9d53a0811ac1.png)
3. Generate G-Code
4. View layer 76, here you can see that the structure is printed in the air and nowhere attached.
 

## Expected behavior

The support should be attached to the rest of the surrounding support or a carrier should be created before the flying support can be placed.

## 🌍  Your Environment

**Platform:**
<pre><code>- Operating System: Windows 10 x64 Version 2004
- Printer: Snapmaker A250
</code></pre>

**Comment by jane-rose** [comment]
Sorry, we can't reproduce it. Or your can send the project file to us. Try to rotate or move the model to see if this bug still occurs

**Comment by mr-manuel** [comment]
Yes sure. If I rotate the oject there are only flat surfaces, so the error could not appear. Here the project file: 
[test.zip](https://github.com/Snapmaker/Luban/files/6333848/test.zip)

**Comment by jane-rose** [comment]
It's a problem with cura. At this time, you may change the support settings like density to aviod this

**Comment by sumibin** [comment]
The issue has been fixed.
