### ISSUE TITLE
Feature Request: luban should indicate you when the velocity you provided is avobe the maxium

### ISSUE THREAD

**Issue by pauserratgutierrez** [Snapmaker/Luban#976]
# 🐞 feature request

### Is your feature request related to a problem? Please describe.

We shouldn't be able to go over the maxium velocity of each motor. Luban should indicate you if the value you provided is impossible for the machine to make a move because of max velocity.
![image](https://user-images.githubusercontent.com/73240206/115989800-64e58780-a5c0-11eb-9ef2-794e9d8846f8.png)

### Describe the solution you'd like?

Make the velocity imput not able to go over a certain max value of the machine

**Comment by parachvte** [comment]
Put onto backlog.

**Comment by paauserrat** [comment]
Amazing. Just to inform, it should be added into every velocity input of luban (not only to 3D moves and retraction velocity... but also to CNC and Laser velocities)

**Comment by sumibin** [comment]
Given that the maximum speed has been limited in the firmware. (Luban also currently has restrictions on it.)This issue will be closed.
