### ISSUE TITLE
Bug: Button is hidden behind remove background button in Laser

### ISSUE THREAD

**Issue by pauserratgutierrez** [Snapmaker/Luban#986]
# 🐞 bug report

The version 3.15.0 introduced new things. One of them is a new blue button in the top right corner. In the laser page in luban, this button is hidden by another button, the remove background.

![image](https://user-images.githubusercontent.com/73240206/116552990-f115e880-a8f9-11eb-8803-9115100f27c8.png)

**Comment by paauserrat** [comment]
The hidden button is "Back to object view".

**Comment by Galindorf** [comment]
Can confirm: This is really annoying. With the Luban update I could not find where to configure my laser settings... I had no idea the Object View was there and I could not find how to even select an object to make a tool path OF!

**Comment by jane-rose** [comment]
OK, we got it.
