### ISSUE TITLE
Bug: stl import to cnc 

### ISSUE THREAD

**Issue by gysnst2** [Snapmaker/Luban#990]
# 🐞 bug report

### Affected Version(s)
 wrong orientation when importing a stl to cnc but correct orientation with importation to 3D printing.  Cannot adjust orientation in cnc 
 The issue is caused by version x.y.z

### Is this a regression? (optional)

 Na 
 Yes, the previous version in which this bug was not present was: ....

### To Reproduce
1. Go to '...'go to cnc 
2. Click on '....' import add stl 
4. See error wrong orientation imported but cannot adjust to make the stl sit properly 
 A clear and concise description of the problem... add import stl in 3D printing orientation correct.  
![image](https://user-images.githubusercontent.com/32149597/116947161-a1a92280-ac41-11eb-8d19-350f8465072a.jpeg)
![image](https://user-images.githubusercontent.com/32149597/116947311-0bc1c780-ac42-11eb-8a4a-d1d752ea6ac8.jpeg)
![image](https://user-images.githubusercontent.com/32149597/116947224-cb624980-ac41-11eb-8d68-8682071ba9e1.jpeg)

Exception or Error (optional)
<pre><code>

</code></pre>

Expected behavior

## 🌍  Your Environment

**Platform:**
<pre><code>
 windows 10 LuBan 3.15. A 350 

- Operating System: [Windows 10 x64, macOS Big Sur, Ubuntu 20.04, etc]
- Printer: [Snapmaker Original, Snapmaker A150, etc]

</code></pre>

**Comment by parachvte** [comment]
There is an option called "Placement Face" where you can change the orientation.
